### PR TITLE
Enable jetty gzip module to compress static files (js, css, ...)

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Nice, but it should be activated by default for all webapps IMO.

**Comment by Vampouille** [comment]
317a016 add gzip module on all webapps

**Comment by fvanderbiest** [comment]
LGTM.
@pmauduit any objection ?

**Comment by pmauduit** [comment]
> @pmauduit any objection ?

No, it looks good, I think we can still manage to get files without compression by tweaking the request headers if we need anyway (for debugging purposes)

**Pull request merged**
