### PR TITLE
geonetwork - upgrade to GN 4.2.2

### PR DESCRIPTION
**Pull request by pmauduit**

### CODE REVIEW

**Comment by landryb** [comment]
Nice ! 

what about all the commits that were added on top of 4.0.6 that arent apparently in 4.2.0 ? cf https://github.com/georchestra/geonetwork/compare/georchestra-gn4-4.2.0...georchestra-gn4-4.0.6 & georchestra/geonetwork#210, georchestra/geonetwork#212, georchestra/geonetwork#212, georchestra/geonetwork#213 & georchestra/geonetwork#215

**Comment by pmauduit** [comment]
> what about all the commits that were added on top of 4.0.6 that arent apparently in 4.2.0 ?
 
no idea tbh, I wasn't the one who worked on the 4.2 branch in the first place :(

**Comment by pmauduit** [comment]
* https://github.com/georchestra/geonetwork/issues/210 : not relevant (targeting master as 4.2.0 targets geor/master)
* https://github.com/georchestra/geonetwork/pull/212 : probably needed if your work hasn't been merged upstream
* https://github.com/georchestra/geonetwork/pull/213 : I don't know if this is already fixed / unecessary on 4.2.0, I'll leave it to @jahow

**Comment by landryb** [comment]
> * [Add support to geopublish geopackage and zipped geopackage geonetwork#212](https://github.com/georchestra/geonetwork/pull/212) : probably needed if your work hasn't been merged upstream

sadly still pending .. geonetwork/core-geonetwork#6490

**Comment by jahow** [comment]
I merged the branch `georchestra-gn4-4.0.6` into `georchestra-gn4-4.2.0` 3 month ago, when it was at this commit: https://github.com/georchestra/geonetwork/commit/649dffdb29c9a9a0fd09b3a1fb630eceafdc30f8

https://github.com/georchestra/geonetwork/pull/213 is not needed in 4.2.0 since this branch contains the "full multilingual package"

But I think the best way forward would be to merge again `georchestra-gn4-4.0.6` into `georchestra-gn4-4.2.0`; I've tried it and there are almost no conflicts.

**Comment by jahow** [comment]
The `georchestra-gn4-4.2.0` branch should now contain all improvements made on 4.0.6, see https://github.com/georchestra/geonetwork/commit/0e5d9f2646fa25e5369c2143963ae7c3e67cbad0

**Comment by landryb** [comment]
thanks @jahow !

**Comment by fvanderbiest** [comment]
Is this PR still relevant ?
It targets `georchestra-gn4-4.2.0` but it seems `georchestra-gn4.2.x` is more up-to-date ?

see also https://github.com/georchestra/georchestra/issues/3868 and https://github.com/georchestra/georchestra/issues/3891

**Comment by jahow** [comment]
Updated this branch to target https://github.com/georchestra/geonetwork/tree/georchestra-gn4.2.x

**Comment by landryb** [comment]
shouldn't the submodule branch in .gitmodules be updated too ? (real question, we wondered about it with @pmauduit for geoserver)

**Comment by fvanderbiest** [comment]
> I guess it's better that way

Definitely !
Dependabot uses this information to submit PRs when commits are added on top of this branch, to keep submodules up to date :-)

Thanks Olivia.

**Comment by fvanderbiest** [comment]
Who's available for a review ? @pmauduit @cmangeat @landryb ?
Thanks !

**Comment by fvanderbiest** [comment]
Well, let's merge: it goes in the right direction.
We'll perform full tests on master for the release.

**Comment by jahow** [comment]
Thanks for pushing this forward. Somehow it broke the integration tests; I have no idea how much those tests are tied to a specific GN version...

**Pull request merged**
