### PR TITLE
security-proxy - Add sec-orgname header with human readable name of org

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
`sec-orgname` header was previously provided by 'o' field from user ldap entry : See: https://github.com/georchestra/datadir/pull/51

**Comment by fvanderbiest** [comment]
We currently have several places in the code where `sec-org` is used:
```
downloadform/src/main/java/org/georchestra/dlform/DownloadQuery.java:        company = request.getHeader("sec-org") != null ?
downloadform/src/main/java/org/georchestra/dlform/DownloadQuery.java:                request.getHeader("sec-org") : request.getParameter("company");
downloadform/src/test/java/org/georchestra/dlform/AbstractApplicationTest.java:        Mockito.when(req.getHeader("sec-org")).thenReturn("geOrchestra");
extractorapp/src/main/filtered-resources/WEB-INF/jsp/index.jsp:        GEOR.data.company = "<%=(request.getHeader("sec-org") == null ? "" : request.getHeader("sec-org"))%>";
extractorapp/src/main/java/org/georchestra/extractorapp/ws/extractor/ExtractorController.java:                String org = request.getHeader("sec-org");
mapfishapp/src/main/filtered-resources/WEB-INF/jsp/index.jsp:        GEOR.config.USERORG = "<%=request.getHeader("sec-org") %>" === "null" ? "" : "<%=request.getHeader("sec-org") %>";
```

Since `sec-org` was previously mapped onto the user's `o` field, maybe we should not introduce `sec-orgname` for 16.12, but rather re-use `sec-org` for backward compatibility ?

**Comment by fvanderbiest** [comment]
2 things here:
 * replace all `sec-org` occurences (dlform, extractorapp) in the code with `sec-orgname`
 * document this change in the release notes.

**Comment by fvanderbiest** [comment]
> 2 things here:
> 
> replace all sec-org occurences (dlform, extractorapp) in the code with sec-orgname
> document this change in the release notes.

To be done in https://github.com/georchestra/georchestra/pull/1669

**Pull request closed without merging**
