### PR TITLE
LDAP - reorganize files for docker image

### PR DESCRIPTION
**Pull request by fvanderbiest**
This change allows to only `COPY docker-root /` in the dockerfile.
The drawback (which is not really one) is that symlincks have to be used to not duplicate LDIF files.

This also emphasizes the fact that we had two `memberof.ldif` files (see #2544), one of which was unused.

Regarding the inclusion of `ldap-utils` & `procps`:
 * `procps` is required, see #1835 
 * `ldap-utils` is a nice-to-have which only adds 1Mb on a 150Mb image. Leaving it.

### CODE REVIEW

**Comment by landryb** [comment]
Fwiw this part of the PR for 3/4 files seems weird: https://github.com/georchestra/georchestra/pull/2715/commits/213a08530e183b713ae14b989a6408e2a1e79590#diff-0baf0f56c9b48799dd931323cd72377c

an ldif file containing a path to another ldif file ? that's sure to confuse users.... or was it supposed to be a symlink ?

**Comment by fvanderbiest** [comment]
Right, it's a symlink.

**Comment by landryb** [comment]
ah well, "interesting". Then people downloading files from the github web UI are confused :)

**Comment by fvanderbiest** [comment]
I tried hard to find the best solution avoiding duplication and complexity, but it seems like there is no silver bullet here

**Comment by landryb** [comment]
Fwiw, as a side effect, i just realized this completely broke the ansible playbook deployments, so far beyond repair.  The 19.04 branch is also broken by e3e4dc082ca but maybe i can fix this one 'easily'..

i'm considering just marking the ansible repo as abandoned, since changes in georchestra are done without (apparently) testing anything outside docker deployment... there's more and more deviation/discrepancy between the 'follow the traditional docs' and "i dont give a f*** i just run docker-compose-yolo". Yes, i'm saddened by this sorry state :)

**Comment by fvanderbiest** [comment]
Thanks Landry for the head-up.
As you can imagine, we do not break things on purpose, it's just a matter of available time.
Before each release I try to check / fix / help with the ansible deployment on my professional time.

But you're right, there's an open question about who's maintaining it & with which resources & for what purpose ...

**Pull request merged**
