### PR TITLE
Listen on unix socket

### PR DESCRIPTION
**Pull request by mcanevet**
Required for backup via slapcat

### CODE REVIEW

**Comment by pmauduit** [comment]
Looks good, but from what I remember, slapcat will also dump the extra ldap attributes (uuid, ...). What is your way of restoring a ldif backup ? (if ldapadd, it won't work because of some read-only attributes), poke @Vampouille (since we discussed this issue some minutes ago).

**Comment by Vampouille** [comment]
You can filter read-only attributes and restore only writable one with ldapadd. This way we can restore ldap with `slapadd` or `ldapadd`.
:+1:

**Comment by pmauduit** [comment]
ok

**Comment by landryb** [comment]
> You can filter read-only attributes and restore only writable one with ldapadd. This way we can restore ldap with slapadd or ldapadd.

Which option of ldapadd or slapcat is this ? Is it a complex slapcat -a filter, manually excluding all the operational attributes ? So far i'm using
```
slapcat | egrep -v '^(contextCSN|entryCSN|modifiersName|modifyTimestampentryUUID)'
```
but if there's a better way i'm all ears :)

**Comment by Vampouille** [comment]
Unix socket is not needed for backup and following commit improve ldap image :
0cbeb505e3f65e3c1734243bb85bcb04790d6bd8

**Pull request closed without merging**
