### PR TITLE
[mapfishapp] Traveler/isochrone addon

### PR DESCRIPTION
**Pull request by landryb**
As promised here's a PR to merge the traveler/route/isochrone addon made by @Gaetanbrl for the GCS-santé when working for GFI - as discussed with @pierrejego the license in the contract between GFI & GCS specified that developments had to be reversed - please correct me if i'm wrong - this legal stuff can be hairy.

I've taken the code/commits from https://github.com/GFI-Informatique/georchestra/tree/traveler/mapfishapp/src/main/webapp/app/addons/traveler - the traveler branch was more advanced than `isochrone` and `itineraire` - cherrypicked @Gaetanbrl commits, and put some fixes on top (mostly css fixes, smallish bugfixes, removed the need to be a connected user, etc..)

I've left the 'referentials' feature in the code but i have to admit i've locally disabled it, since i think its usecase is to work with a datastore that provides POIs and i dont have a usecase for it. This bit probably needs refinement (ie make it configurable to use referentials or not)

As is, it works fine in production for us.. wont be able to spend much time on it, so feel free to pick it up from there :)

### CODE REVIEW

**Comment by pierrejego** [comment]
Thanks !!! 
I never took the time to do it....
And you are right with the orignal licence, it's free  to use, reuse, modifiy. Same as geOrchestra

Regards

**Comment by fvanderbiest** [comment]
mapfishapp EOL. Closing.

**Comment by landryb** [comment]
even if EOL, if some people were using this tool in some installations they will need to adapt to the new API provided by IGN, cf https://geoservices.ign.fr/documentation/services/api-et-services-ogc/itineraires/adaptation-au-nouveau-service

**Comment by Gaetanbrl** [comment]
even if EOL, here a usefull example about route calculation (from [IGN doc](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/itineraires)): 

https://jsfiddle.net/ignfgeoportail/1nvqgyhs/

**Pull request closed without merging**
