### PR TITLE
datafeeder integration - adding a maven module to build the UI

### PR DESCRIPTION
**Pull request by pmauduit**
See the added README.md for the considerations of why it could make sense to be able to have the ui in a separate module and provided as a WAR package.

### CODE REVIEW

**Comment by landryb** [comment]
for consistency with other modules, why not `datafeeder-ui.war` instead of `import.war` ?

**Comment by pmauduit** [comment]
> for consistency with other modules, why not datafeeder-ui.war instead of import.war ?

For now, the web ui expects to be behind `/import/`. Is it a must to be able to put it wherever you want ?

**Comment by landryb** [comment]
ah then it makes sense, it's just that some things in buildbot and ansible playbook tend to assume that the war has the same name as the folder, but i might remember wrong

**Comment by pmauduit** [comment]
> ah then it makes sense, it's just that some things in buildbot and ansible playbook tend to assume that the war has the same name as the folder, but i might remember wrong

I can rename the directory to "import", but I made more sense to me to have datafeeder (backend) + datafeeder-ui (frontend).

**Comment by pmauduit** [comment]
> ah then it makes sense, it's just that some things in buildbot and ansible playbook tend to assume that the war has the same name as the folder, but i might remember wrong

You can customize the final generated artifact name at several places, and it depends on the involved maven plugin. For maven-war-plugin, it normally uses the <artifactid>-<version>.war convention, but if a finalName property is defined, then it will name it following the property. This is what we actually use in the debianPackage profile so that we can have a "predictible" path in the debian package setup.

**Review by groldan — APPROVED** [review]
LGTM

**Pull request merged**
