### PR TITLE
mapfishapp: Fix support for uploading KML files and convert to GeoJSON for display

### PR DESCRIPTION
**Pull request by groldan**
This PR depends on #2676 and the following GeoTools PR to be backported to 21.x: geotools/geotools/pull/2523

Fixes several issues with KML upload to mapfishapp and getting a GeoJSON response:

### Response content-type: 
The API returns application/json as response content type, except if the request explicitly asks for text/html, which is the case for the Ext.js submitted form when uploading a file. In this case text/html is returned to avoid an error/warning on the Javascript client side.
    
### KML file parsing improvements (KmlFeatureSource):
* Parsing to FeatureCollection made streaming, it was loading all the Features in memory.
* Added on-the fly reprojection through FeatureCollection decorator
* Force the default geometry attribute to be the "Geometry" attribute, the GeoTools parser returns Features whose schema's default geometry attribute is "LookAt", since it occurs before "Geometry",
and results in no geometry being encoded to GeoJSON, which takes the default geometry as the GeoJSON "geometry" property.
* Remove the "Style" attribute through a feature collection decorator, the GeoTools parser sets it to a FeatureTypeImpl instance which gets encoded to GeoJSON as FetureTypeImpl.toString(), which makes no sense.

Several other fixes and improvements, check the PR's commit list.

### CODE REVIEW

**Comment by groldan** [comment]
GeoTools backport PR: geotools/geotools/pull/2523. Once travis finishes I'll merge it, then once Jenkins publishes the artifacts this PR should build fine.

**Comment by fvanderbiest** [comment]
Excellent !
Thanks a bunch Gabriel.

Can you rebase on top of master, so we don't ship commits from #2676 ?

**Comment by groldan** [comment]
Yep, that's the idea, I'll do, thanks for the review

**Comment by groldan** [comment]
@fvanderbiest rebased.

**Pull request merged**
