### PR TITLE
Console - harmonize properties

### PR DESCRIPTION
**Pull request by severo**
Note that we removed two classes, and that we used `@Value` in some classes to access the datadir properties files, since they use the `@Controller` annotation, and do not appear in the Spring XML configuration file.

If using `@Value` is a good idea or not could be discussed (see https://github.com/georchestra/georchestra/issues/2379#issuecomment-463246745), but I did it to stick at most to #2496, and remove all occurrences of the `getProperty` method of the `GeorchestraConfiguration` class.

### CODE REVIEW

**Comment by severo** [comment]
Oups, build failed.... Will fix it tomorrow

**Comment by severo** [comment]
I had forgot to launch the integration tests (with `mvn -Pit verify`). Maybe they should be launched by default? What do you say?

To fix, I:
- used git bisect to find the guilty commit - see https://delicious-insights.com/fr/articles/git-bisect/
- edit the history to insert the fix inside the guilty commit - see https://stackoverflow.com/questions/8824971/how-to-amend-older-git-commit/18150592#18150592

**Comment by fvanderbiest** [comment]
> I had forgotten to launch the integration tests (with `mvn -Pit verify`). Maybe they should be launched by default? What do you say?

Already done via 7051fec3e6cdb33d80f79cdc54b444f7819d691d ?

**Comment by severo** [comment]
Yes, thanks to this, I have been warned of the error.
I mentioned when launching locally `mvn jetty:run`, or `mvn install`, for example

**Comment by fvanderbiest** [comment]
There are still places where `GeorchestraConfiguration` is used. Is it expected ?

**Comment by severo** [comment]
Yes, I'm only removing the occurrences where the `getProperty` method of the `GeorchestraConfiguration` is used, ie. removing the use of that class to access default.properties and the `console/console.properties` file (and similar one for the other applications).

But there are other methods that allow to access files in the datadir, or load other properties files... I let them for the moment. Maybe #2379 will lead to also remove these others uses.

**Pull request merged**
