### PR TITLE
mapfishapp querier: bufferSupport

### PR DESCRIPTION
**Pull request by fvanderbiest**
This PR provides the client-side work related to https://github.com/georchestra/georchestra/issues/1015

It replaces https://github.com/georchestra/georchestra/pull/1332

### CODE REVIEW

**Comment by fvanderbiest** [comment]
This is WIP, but looks promising

capture du 2016-04-01 16 56 25

**Comment by fvanderbiest** [comment]
https://github.com/georchestra/styler/pull/13 being merged, this one is ready.

Example UI:
capture du 2016-04-04 18 29 42

**Comment by fvanderbiest** [comment]
Deployed to https://sdi.georchestra.org/mapfishapp/

**Comment by jdenisgiguere** [comment]
Thank your @fvanderbiest . UI is much more intuitive.

**Comment by fvanderbiest** [comment]
A nice screenshot showing a cross layer request with a buffer.
capture du 2017-02-15 11-06-12

**Pull request merged**
