### PR TITLE
GN3 - empty wro4jUrlsToInitialize to fix HTTP 301 or 302 caching

### PR DESCRIPTION
**Pull request by fvanderbiest**
This PR updates GN3 submodule on 15.12 version (to be cascade merged) to fix incorrect caching of JS files.

The symptom was "emtpy pages on GN3" with a JS error.

https://georchestra.mydomain.org/geonetwork/static/gn_admin.js contents: 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://georchestra.mydomain.org/static/gn_admin.js/catalog/components/admin/schematron/SchematronAdminService.js">here</a>.</p>
</body></html>

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://georchestra.mydomain.org/static/gn_admin.js/catalog/components/admin/schematron/SchematronEditCriteriaDirective.js">here</a>.</p>
</body></html>

...
```

The related commit in GN3 is https://github.com/georchestra/geonetwork/commit/60c7869cd703fa60d889f2cb223c26321fa81ff6

### CODE REVIEW

**Comment by fvanderbiest** [comment]
ping @fxprunayre @fgravin to eventually take it into account upstream

**Comment by landryb** [comment]
Isnt it totally disabling/bypassing wro4j ?

**Comment by fvanderbiest** [comment]
no, it's only removing the warmup.

**Comment by fxprunayre** [comment]
> ping @fxprunayre @fgravin to eventually take it into account upstream

Indeed I think we should apply (even drop warmup unless we improve it). I think the case we're facing is that wro4j tries to warmup before the app (and the optional proxy in front) is up and running. @fgravin , what do you think ?

**Comment by fgravin** [comment]
It seems it almost only happens in geOrchestra, and it happened almost on all instances of geOrchestra, seems related to the SDI architecture.

I think warmup is a good thing for common usage (gn in simple tomcat).
I would keep it.

**Comment by fvanderbiest** [comment]
> it happened almost on all instances of geOrchestra

That's incorrect, since georhena, ppige, geopicardie, cigalsace ... are unaffected.

**Comment by fxprunayre** [comment]
> only happens in geOrchestra

I also got it on a Apache reverseproxy AJP > Tomcat.

**Pull request merged**
