### PR TITLE
Measurements addon

### PR DESCRIPTION
**Pull request by fvanderbiest**
This PR is related to improvement #1011 
It replaces #1078 

Current status: work in progress.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks for this work @jdenisgiguere !

Several comments:
 * KML export works great, but surfaces are filled : can we make them transparent ?
capture du 2016-03-14 10 07 49
 * point features are not useful in KML export, do you think we could remove / hide them ?
 * do you think we could add attributes to the exported features so that measures appear when features  clicked in Google Earth ?
capture du 2016-03-14 10 10 28
 * clicking on the export button changes the clear button state
capture du 2016-03-14 10 12 19
 * there's an issue when deactivating the addon (with measurements in the layer) then reactivating it : ghost measures are shown:
capture du 2016-03-14 10 13 48

**Comment by fvanderbiest** [comment]
In addition, there's an issue while printing:

```
Error while generating PDF:
java.lang.IllegalArgumentException: Invalid number of points in LinearRing (found 2 - must be 0 or >= 4)
	at com.vividsolutions.jts.geom.LinearRing.validateConstruction(LinearRing.java:114)
	at com.vividsolutions.jts.geom.LinearRing.<init>(LinearRing.java:106)
	at com.vividsolutions.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:341)
	at com.vividsolutions.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:328)
```

Can you investigate it and tell us if the client is generating erroneous geometries or if the server-side component is too strict ?

**Comment by landryb** [comment]
Reminder.. there's also #1205 pending in the same area :)

**Comment by fvanderbiest** [comment]
> Reminder.. there's also #1205 pending in the same area :)

Yes, I have reviewed it, and it needs more work from the author.

**Comment by jdenisgiguere** [comment]
> KML export works great, but surfaces are filled : can we make them transparent ? 

OpenLayers KML export do not export Style. We have to add style information:
* Option A : using KML string manipulation (append style information at root and to every features);
* Option B: parsing OpenLayers KML, then manipulating object.

**Comment by fvanderbiest** [comment]
Let's go for the shorter one ... I guess A ?

**Comment by jdenisgiguere** [comment]
Updated KML export screenshot:
kmlexport

**Comment by fvanderbiest** [comment]
> Updated KML export screenshot:

This looks very good now, thanks Jean-Denis.

**Comment by fvanderbiest** [comment]
Funnily, my Google Earth engine v7.1.4.1529/linux still displays filled polygons ...

**Comment by jdenisgiguere** [comment]
Pull request (https://github.com/jorix/OL-DynamicMeasure/pull/9) for the modifications to the DynamicMeasure control is sent.

**Comment by fvanderbiest** [comment]
With 56e2b75 I've enhanced code readability + refactored, but, doing so, I think I broke the KML export of lines and polygons... and I'm running out of time.

Can you have a look at it ? Thanks :-)

**Comment by jdenisgiguere** [comment]
Thanks @fvanderbiest ! code readability and coherence with other add-on is greatly improved!
KML export is fixed in a2ae498.

**Comment by fvanderbiest** [comment]
This PR now integrates the fix for printing layers with invalid geometries.

It's nearly ready for merge, but I'd like @jdenisgiguere to investigate the possibility to improve the print measures readability, eg:
capture du 2016-03-18 13 54 44

Maybe adding a 1px white outline to texts in the feature style, and decreasing point size could make it.

**Comment by fvanderbiest** [comment]
Now this looks good for merge.

capture du 2016-03-18 17 00 37

What do you think @jdenisgiguere ?

**Comment by jdenisgiguere** [comment]
Should we make the difference between the 2 measurements add-ons (simple and multiple) in the tools selection menu easier to understand? Currently they have the same title and same description.

**Comment by fvanderbiest** [comment]
> Should we make the difference between the 2 measurements add-ons (simple and multiple) in the tools selection menu easier to understand? Currently they have the same title and same description.

Right, fixed with 5004560

**Pull request merged**
