### PR TITLE
LDAP - adding a schema to store ssh keys on users

### PR DESCRIPTION
**Pull request by pmauduit**
Tests: docker build, ldapsearch OK

### CODE REVIEW

**Comment by landryb** [comment]
What's that 'openssh' ldap module ? What's the usecase, sftp i access i guess ?

**Comment by fvanderbiest** [comment]
> What's the usecase, sftp i access i guess ?

That's it. 
It'll be much more convenient to have public keys on a local LDAP than elsewhere...

**Comment by fvanderbiest** [comment]
Merging, will fix the "Too many ADD" in a second time.

**Comment by fvanderbiest** [comment]
> will fix the "Too many ADD" in a second time.

see #2715 on master

**Comment by landryb** [comment]
something might be wrong somewhere, because on a clean dit when i try saving a user the backend blows:
```
2019-09-23 15:18:45 GlobalExceptionHandler [ERROR] org.springframework.ldap.SchemaViolationException: [LDAP: error code 65 - attribute 'sshPublicKey' not allowed]; nested exception is javax.naming.directory.SchemaViolationException: [LDAP: error code 65 - attribute 'sshPublicKey' not allowed]; remaining name 'uid=testadmin,ou=users'
        at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:219)
        at org.springframework.ldap.core.LdapTemplate.executeWithContext(LdapTemplate.java:820)
        at org.springframework.ldap.core.LdapTemplate.executeReadWrite(LdapTemplate.java:812)
        at org.springframework.ldap.core.LdapTemplate.modifyAttributes(LdapTemplate.java:964)
        at org.springframework.ldap.core.LdapTemplate.modifyAttributes(LdapTemplate.java:1317)
        at org.georchestra.console.ds.AccountDaoImpl.update(AccountDaoImpl.java:205)
        at org.georchestra.console.ds.AccountDaoImpl.update(AccountDaoImpl.java:215)
        at org.georchestra.console.ws.backoffice.users.UsersController.update(UsersController.java:455)
```

in the DIT, the user has the correct objectClass afaict:
```
# testadmin, users, georchestra.org
dn: uid=testadmin,ou=users,dc=georchestra,dc=org
objectClass: organizationalPerson
objectClass: person
objectClass: inetOrgPerson
objectClass: shadowAccount
objectClass: top
objectClass: ldapPublicKey
uid: testadmin
givenName: Test
sn: ADMIN
description: Admin user
sshPublicKey: AAAAB3NzaC1yc2EAAAADAQABAAABAQDZYjTbscNq9hfHPW9A/yfsr9n+emySaq6N
 yXeHeK3co0zCj117WHNUq0LpQa4kqbhwa+uEw2cDqMelhgaRpAjXaxEr3riKfCvqyLfBn2E2n11Hw
 B083uaHrnr3rdzlm2TSPwKxpjrzeKoZZzWnemGnfuzd0LmBDWce7y0q3MnEpN3M0BbCAknfK/JSbG
 Y304Ikhp8Byla2BTEaWEsBZy+4CIkEdJyNDMg/2PAMZMpnVn3EYOkt5Fj8apIOvmculTnZcVSKACF
 7d+QB5Xddq2QwUYTQR4Ga82xnG1PzmuoIyWZufJpQHLSQ+25Z8FIqDMXtvuB3AZKVwlPpY5ojncXX
sshPublicKey: AAAAB3NzaC1yc2EAAAADAQABAAABAQDD3ZcO+iVIVUZQakEFowQ2NR2J6xe2MMV9
 ezZlxttS7/E/UhLn4dXnqgUETht4yRygwzu3y7BG9K0iT7YF4BMHEshpXiOos6yGG+NSIP6wND+7w
 j1UoDkcz0Fyis+7okO4l/NHPCYb4VVD/rcocGHDebusHPemccFqtoCdrUTh3xk4pPbqV9D4Ojppfg
 /oUzQVyo/kbiQ3GGnuokMpf7uAGFWp/jOoKWfIBbNauOmyx+6yNO9PoDP3wD1jf1MpFuJQszHZbPe
 5r8T7UOk6dhOkbKPfwRLdFqEWaxqI1Fhv8o6WTtffOk+V91MZbmxGx5QJ9/6crg0k+meKSowGHOQB
mail: psc+testadmin@georchestra.org
cn: testadmin
```

**Pull request merged**
