### PR TITLE
Add test data and make them optional with IGNORE_DATA=yes

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
Test data should not be loaded in prod env, so with this commit each files ending with -data.sql will be ignored if IGNORE_DATA=yes is set

**Comment by Vampouille** [comment]
Same apply for ldap service

**Comment by pmauduit** [comment]
Looks good

**Comment by fvanderbiest** [comment]
LGTM, please merge.

**Pull request merged**
