### PR TITLE
restrict search for users in ou=users branch

### PR DESCRIPTION
**Pull request by cmangeat**
https://github.com/georchestra/georchestra/issues/2158

### CODE REVIEW

**Comment by landryb** [comment]
Hardcoding `ou=users` kills kittens. Can you use `userSearchBaseDN` property ?

**Comment by cmangeat** [comment]
Yes I should... It shows that there is a difficulty here:
https://github.com/georchestra/georchestra/pull/2187/commits/adbc2de10a30dc7f49ab8daa7ee0c11949aa4f63#diff-b8c31ceb76dc41c186fc4501a3845b24L251

Have to review all and understand a little what is this unique number for.

**Comment by fvanderbiest** [comment]
LGTM, but requesting another review from @pmauduit

**Comment by landryb** [comment]
Tested working fine at runtime here, i only have entries from `ou=users` instead of the 250+ extra ones from other branches. Thanks !

**Pull request merged**
