### PR TITLE
Set packageRevision to the date of build and the short commit id (#1931)

### PR DESCRIPTION
**Pull request by landryb**
Of course would need to be cherrypicked on 16.12 and 17.12 for the bot to pick them up and do something useful with it..

### CODE REVIEW

**Comment by landryb** [comment]
Hmm, something is wrong, it was okay in my testing on a single pkg, but on a full build on master i get:
```
make deb-build-georchestra
...
...
analytics/target/georchestra-analytics_18.06+201803191055-1_all.deb
atlas/target/georchestra-atlas_18.06+201803191053-1_all.deb
cas-server-webapp/target/georchestra-cas_18.06+201803191044-1_all.deb
console/target/georchestra-console_18.06+201803191051-1_all.deb
extractorapp/target/georchestra-extractorapp_18.06+201803191045-1_all.deb
geonetwork/web/target/georchestra-geonetwork3_3.4.1-0-2018-03-19T09\:44\:16+0000~89fa6c4_all.deb
geoserver/webapp/target/georchestra-geoserver_18.06+201803191045-1_all.deb
geowebcache-webapp/target/georchestra-geowebcache_18.06+201803191046-1_all.deb
header/target/georchestra-header_18.06+201803191056-1_all.deb
mapfishapp/target/georchestra-mapfishapp_18.06+201803191052-1_all.deb
security-proxy/target/georchestra-security-proxy_18.06+201803191054-1_all.deb
```
So it only worked for geonetwork, and it has a wrong date format there. Meh. I'll need to look again.

**Comment by landryb** [comment]
Dammit, was testing the wrong branch, that's what we have in master now it seems ? -SNAPSHOT is replaced by the maven timestamp automatically ? https://github.com/georchestra/geonetwork/pull/63/commits/29fd084dbe2cd0cb12a43ea7a57ca5dd3afc68eb should fix the timestamp on geonetwork package.

**Comment by landryb** [comment]
Ok, so for -master and my commit it seems redundant as maven automagically adds the build date when -SNAPSHOT is in use, but that's not the same time stamp as {maven.build.timestamp}, i get this:
```
analytics/target/georchestra-analytics_18.06+201803191220-20180319-1113~63fc157_all.deb
atlas/target/georchestra-atlas_18.06+201803191218-20180319-1113~63fc157_all.deb
cas-server-webapp/target/georchestra-cas_18.06+201803191213-20180319-1113~63fc157_all.deb
console/target/georchestra-console_18.06+201803191217-20180319-1113~63fc157_all.deb
extractorapp/target/georchestra-extractorapp_18.06+201803191214-20180319-1113~63fc157_all.deb
geonetwork/web/target/georchestra-geonetwork3_3.4.1-0-20180319-1113~63fc157_all.deb
geoserver/webapp/target/georchestra-geoserver_18.06+201803191215-20180319-1113~63fc157_all.deb
geowebcache-webapp/target/georchestra-geowebcache_18.06+201803191215-20180319-1113~63fc157_all.deb
header/target/georchestra-header_18.06+201803191220-20180319-1113~63fc157_all.deb
mapfishapp/target/georchestra-mapfishapp_18.06+201803191218-20180319-1113~63fc157_all.deb
security-proxy/target/georchestra-security-proxy_18.06+201803191219-20180319-1113~63fc157_all.deb
```

the short git commit is correctly appended, but the dates are too much (and differ ?)... need to find a way to tell maven not to automagically replace -SNAPSHOT ?

**Comment by pmauduit** [comment]
> the short git commit is correctly appended, but the dates are too much (and differ ?)... need to find a way to tell maven not to automagically replace -SNAPSHOT ?

From what I read from the maven debian package plugin sources, that is not possible unfortunately

**Comment by fvanderbiest** [comment]
Thanks for the review Pierre !
Conflicts should be resolved before merge.

**Comment by landryb** [comment]
So if we merge this, we all agree that debian packages built from the master branch will have suffixes like `_18.06+201803191220-20180319-1113~63fc157_all.deb` ? i only care/target the stable branches originally...

**Comment by pmauduit** [comment]
> So if we merge this, we all agree that debian packages built from the master branch will have suffixes like _18.06+201803191220-20180319-1113~63fc157_all.deb ? i only care/target the stable branches originally...

I'm fine with that, considering that only the package name matters using apt

**Comment by landryb** [comment]
doesnt seem so, the first timestamps comes from maven and replaces -SNAPSHOT, apparently hardcoded in the maven plugin source.

**Comment by pmauduit** [comment]
@landryb sorry for the delay, could you rebase the branch ? thanks

**Comment by landryb** [comment]
georchestra/geonetwork#70 needs to be merged too if you merged this one, and bump the submodule ?

**Comment by pmauduit** [comment]
GN master related PR: https://github.com/georchestra/geonetwork/pull/70
GN 17.12 related PR: https://github.com/georchestra/geonetwork/pull/72
GN 16.12 related PR: https://github.com/georchestra/geonetwork/pull/71

Since nobody in the geOr community provide debian packages for 16.12 (nor Jenkins nor Buildbot seems to have a job to build this version), can we consider dropping the 16.12 version of this modification ?

**Comment by landryb** [comment]
> Since nobody in the geOr community provide debian packages for 16.12 (nor Jenkins nor Buildbot seems to have a job to build this version)

the default 'buildjob' in the bot is still building 16.12 :)

**Comment by pmauduit** [comment]
> the default 'buildjob' in the bot is still building 16.12 :)

ok, then we just have to merge the last 2 PRs then making the submodules go forward

**Pull request merged**
