### PR TITLE
Mapstore2 - Allow access to gs_* tables and hibernate_sequence

### LINKED ISSUE #3244: [mapstore] - Fix tables and hibernate_sequence access denied error
Port georchestra/mapstore2-georchestra#311 into [postgres/110_mapstore.sql](https://github.com/georchestra/georchestra/blob/master/postgresql/110-mapstore.sql) according to issue georchestra/mapstore2-georchestra#310.

After install georchestra (with ansible) and mapstore2-georchestra (manually from latest [doc](https://docs.georchestra.geo-solutions.it/en/latest/)) i get errors and can't create & save context.

The PR  (suggested in georchestra/mapstore2-georchestra#310) in progress will fix that.

### PR DESCRIPTION
**Pull request by Gaetanbrl**
Fix #3244 by set access right on mapstore tables and hibernate sequence.

### CODE REVIEW

**Review by fvanderbiest — CHANGES_REQUESTED** [review]
The other SQL files in the same directory do not perform any GRANT statement, this is because this hardcodes the role name.
Instead this should belong to the documentation, see https://github.com/georchestra/georchestra/blob/master/docs/setup/postgresql.md

**Comment by Gaetanbrl** [comment]
>  do not perform any GRANT statement

@fvanderbiest  excepted for GN or this concerns SQL files content only ?

`psql -d georchestra -c "GRANT geonetwork TO georchestra;`


> Instead this should belong to the documentation

So, initial version of this script needs to belong the doc (GRANT statement was already accepted before, i'm little bit confused...).

https://github.com/georchestra/georchestra/blob/b59be63d1ee2117279fff68e2830e1a15fd4ac9c/postgresql/110-mapstore.sql#L7-L8

**Comment by Gaetanbrl** [comment]
@fvanderbiest same for geofence ?

https://github.com/georchestra/georchestra/blob/b59be63d1ee2117279fff68e2830e1a15fd4ac9c/postgresql/080-geofence.sql#L3-L4

**Comment by fvanderbiest** [comment]
> @fvanderbiest same for geofence ?

To be fixed ;-)

**Comment by fvanderbiest** [comment]
OK, merging and I will propose a PR to fix the SQL files

**Pull request merged**
