### PR TITLE
Add manager field and fix some old js errors

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by fvanderbiest** [comment]
2 commits / PR would have been better, but ok ...

**Comment by fvanderbiest** [comment]
Tests failing:
```
[ERROR] /home/travis/build/georchestra/georchestra/ldapadmin/src/test/java/org/georchestra/ldapadmin/ws/backoffice/UsersGroupsControllerTest.java:[115,42] error: method createFull in class AccountFactory cannot be applied to given types;
```

**Comment by Vampouille** [comment]
I fix test suite

**Comment by fvanderbiest** [comment]
Thanks !

**Pull request merged**
