### PR TITLE
[console] Allow multiselection of users

### PR DESCRIPTION
**Pull request by tonio**
see https://jira.camptocamp.com/browse/GSHDF-29

### CODE REVIEW

**Comment by fvanderbiest** [comment]
@tonio conflicts to fix

Would be nice if @Gaetanbrl could have a look too.

**Comment by Gaetanbrl** [comment]
How work filter and selection together ? 

If i use filter and click on "select all", i have all users in my selection.
image

That could be be very powerfull to use filter and multiselection together in this particular case and others.

**Comment by Gaetanbrl** [comment]
Additionally, if you select 2 users with manual selection, write something to filter users and check "display selection only"  you have no result.

image

**Comment by tonio** [comment]
> That could be be very powerfull to use filter and multiselection together in this particular case and others.

Good catch, will do.

> Additionally, if you select 2 users with manual selection, write something to filter users and check "display selection only" you have no result.

This one looks correct to me. You're displaying selection, and filter into it…

**Comment by Gaetanbrl** [comment]
> You're displaying selection, and filter into it…
To understand, could you explain me what is the selection display by this checkbox ?
image

**Comment by tonio** [comment]
You display only selected(checked) users.

**Comment by Gaetanbrl** [comment]
Thanks, i was confused because in this case i see the number of selected users, my filter selection (independant of manual selection) and nothing if i check "display only selection" checkbox.

**Pull request merged**
