### PR TITLE
Header app is now aware of MapStore

### PR DESCRIPTION
**Pull request by Gnafu**

### CODE REVIEW

**Comment by landryb** [comment]
looks globally good, but some nits:
- im not sure yet how we want to show the 'mapstore' name to users. Users know what a viewer is, not what mapstore means :) Anyway, every instance will probably customize the header, but its good to have correct defaults.
- the sql script doesnt add all expected categories, which already lead to issues (cf georchestra/mapstore2-georchestra#226) - shouldnt this be handled by some serverside/hibernate stuff instead ?

**Comment by fvanderbiest** [comment]
> * im not sure yet how we want to show the 'mapstore' name to users.

Agreed !
Probably the hardest issue here: naming things ;-)

**Comment by fvanderbiest** [comment]
Is this PR still draft @Gnafu ? Thanks

**Comment by landryb** [comment]
needs update to use `mapstore` instead of `geostore` in the sql file, and some entries are missing in the categories table. Cf https://github.com/georchestra/mapstore2-georchestra/pull/273/files#diff-165ba004e18ad7c5ed9d5fbe6178eeb6R209

**Comment by lpasquali** [comment]
database script updated, reviewed if everything was in place for header

**Comment by lpasquali** [comment]
@fvanderbiest @landryb applied same sql provided for geosrchestra/mapstore2-georchestra

this also fixes georchestra/mapstore2-georchestra/issues/278

**Comment by lpasquali** [comment]
@fvanderbiest I see that git workflow checks fail because of problems further a correct build completion of postgres and header but everything is corrected to mapstore schema here and can be merged

**Comment by landryb** [comment]
woo 🎆 🍾

**Pull request merged**
