### PR TITLE
mapfishapp - deactivate tests if travis is detected

### PR DESCRIPTION
**Pull request by pmauduit**
Title says it all.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
LGTM, but how will we know that travis has restored a working JVM ?

**Comment by pmauduit** [comment]
We won't :)

**Comment by fvanderbiest** [comment]
Hmm, might be good to keep it up in a fork, just in case ?

**Comment by pmauduit** [comment]
> Hmm, might be good to keep it up in a fork, just in case ?

:+1:

**Pull request merged**
