### PR TITLE
Analytics -  API documentation

### PR DESCRIPTION
**Pull request by pmauduit**
Adding a little bit of autogenerated documentation on the analytics module, see http://build.georchestra.org/analytics-apidoc/# for a sample result.

The site can be generated using the following command on the `analytics` module:

```
mvn clean package -Papidoc
```

This will require to complete the documentation into the code, using the annotations (see `StatisticsController.java` for how to do it), but I think it can be merged in this state for now, since the modifications are isolated into a maven profile.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Looks very promising !

**Comment by Vampouille** [comment]
+1

**Comment by fvanderbiest** [comment]
Looks good @pmauduit but you should rebase it if you want it merged before 16.12 :-)

**Comment by pmauduit** [comment]
There you go

**Pull request merged**
