### PR TITLE
Only listen on loopback interface when populating ldap

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
We need to push this on docker hub

**Comment by pmauduit** [comment]
Looks good (but what is the purpose of limiting the interfaces to the loopback ?)

**Comment by Vampouille** [comment]
If ldap server listen on all interface during "populate" script, WaitForLdap class will consider ldap as installed and populated. With this modification, WaitForLdap will wait (as expected) for end of population script.

**Comment by fvanderbiest** [comment]
> If ldap server listens on all interfaces during "populate" script, WaitForLdap class will consider ldap as installed and populated. With this modification, WaitForLdap will wait (as expected) for end of population script.

Thanks Julien.
It's always a good idea to give some context with a PR.

**Pull request merged**
