### PR TITLE
[Mapfishapp] Backgrounds addon

### PR DESCRIPTION
**Pull request by jusabatier**
This addon add a button to the toolbar which allow to select a WMTS background layer for the map in a configured list.

Only one of the list's layer will be loaded, select another one will replace the previous one.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks Julien.
Will review when the indents conform to our [contributing guidelines](https://github.com/georchestra/georchestra/blob/15.06/CONTRIBUTING.md) (4 spaces)

**Comment by jusabatier** [comment]
I changed this, I will take care with this in my futures commits.

I discovered that I can do that very quickly with the "change tab to space" function of notepad++ :)

**Comment by fvanderbiest** [comment]
Sorry for not being reactive on this one...

**Comment by fvanderbiest** [comment]
It will be part of the 17.12 release. Congrats !

**Comment by fvanderbiest** [comment]
Config shiped with default datadir with https://github.com/georchestra/datadir/commit/0b06f4093319c579a9afb7ed2e7d16c9295916bc

**Pull request merged**
