### PR TITLE
Solve annotation dependency problem with Java11 for geOrchestra's commons

### PR DESCRIPTION
**Pull request by jusabatier**
Correct https://github.com/georchestra/georchestra/issues/3182

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks Julien !
Pierre will have a look when he's back.

**Comment by pmauduit** [comment]
Not related to the PR, but the GH actions are failing, we shall make sure that the "login onto docker.io" step is skipped once not on the georchestra organization. Actually this is weird, as it should already be the case:
https://github.com/georchestra/georchestra/blob/master/.github/workflows/analytics.yml#L58

Regarding the PR, adding the dependency is ok for me, but I'd have done it in a profile, as adding the dependency is not necessary in former Java versions. Also, the `@PostConstruct` annotation has also been introduced in some other modules (SP, console ...). As they depend on georchestra-commons, it is probably ok to keep it this way, but I'd prefer have the dependency explicitely required each time we need it.

**Comment by fvanderbiest** [comment]
@jusabatier would you be able to rework the PR as advised by Pierre ? Thanks !

**Comment by jusabatier** [comment]
> dependency is not necessary in former Java versions

Isn't version 20.1 of georchestra supposed to be deployed in Debian Buster (10) ?
In this case, JAVA 11 is the default version, so I don't understand why create a profile for support the default version...
It only can make the build of georchestra more complex to understand by adding an unnecessary profile to set.

**Comment by jusabatier** [comment]
This issue still block the compilation with JAVA11.

So for now it's difficult to compile war of latest release (21.1.1)

**Comment by fvanderbiest** [comment]
OK, what is the status of this PR ? 
Seems it cannot be merged as is, since there are conflicts.

**Comment by jusabatier** [comment]
Conflits corrected

**Comment by fvanderbiest** [comment]
@pmauduit can you review a second time or take over ? Thanks !

**Comment by jusabatier** [comment]
Wait a little, I get some errors linked to this compiling GN.
I'm checking out what is blicking and will add a commit for this.

**Comment by jusabatier** [comment]
Sorry, as GN is a separate repo, you can check and merge this PR

**Comment by pmauduit** [comment]
superseded by #3581

**Pull request closed without merging**
