### PR TITLE
[GSHDF-51] Add geoserver support for kakadu 7.x JPEG2000 coverages

### PR DESCRIPTION
**Pull request by groldan**

### CODE REVIEW

**Comment by groldan** [comment]
@pmauduit @fvanderbiest you'll need georchestra/docker#25 applied to the docker checkout

**Comment by fvanderbiest** [comment]
Thanks Gabriel. I appreciate the doc.

One question though. How did you generate those files ?
```
geoserver/lib/2.12.5/imageio-ext-kakadu-1.1.18.jar 
geoserver/lib/2.12.5/imageio-ext-kakadujni-5.2.6.jar 
```

**Comment by pmauduit** [comment]
> geoserver/lib/2.12.5/imageio-ext-kakadu-1.1.18.jar 

This one comes from https://github.com/geosolutions-it/imageio-ext/tree/master/plugin/kakadujp2

> geoserver/lib/2.12.5/imageio-ext-kakadujni-5.2.6.jar

This one has be removed: it is provided by the Kakadu SDK, and since we are using a more recent version (7.x), having this one in the webapp's classpath can be problematic. I guess that @groldan provided a 7.x version renamed to 5.2.6 in order to override the one which comes with imageio-ext-kakadu-1.1.18 by transitive dependency, but are we allowed to version the jar, as the license of the SDK is quite restrictive ?

**Comment by fvanderbiest** [comment]
> are we allowed to version the jar, as the license of the SDK is quite restrictive ?

Asking the guys at http://kakadusoftware.com/

**Comment by pmauduit** [comment]
Anyway, I do need the jp2k maven profile defined in this PR !

**Comment by groldan** [comment]
FYI, issued a PR to imageio-ext to handle the jni lib version incompatibility: https://github.com/geosolutions-it/imageio-ext/pull/207

**Comment by groldan** [comment]
PR updated, able to serve jp2k rasters both as single coverage and image mosaic.
Tested image mosaic with 8 images from Nasa's `world.topo.bathy` dataset that are 21600x21600 pixels each.

**Comment by fvanderbiest** [comment]
Excellent Gabriel !
Thanks also for the `git-commit-id-plugin` upgrade.

**Pull request merged**
