### PR TITLE
GS 2.22.2 - bumping GS version

### PR DESCRIPTION
**Pull request by pmauduit**
See other PRs for the context, eg.:
https://github.com/georchestra/georchestra/pull/3901#issue-1594580686

Mainly to address https://github.com/geoserver/geoserver/security/advisories/GHSA-7g5f-wrx8-5ccf

Tests: runtime tested with some very light tests.

### CODE REVIEW

**Comment by landryb** [comment]
deployed on https://demo.georchestra.org/geoserver/web, works fine. as already seen, some versions arent properly shown on the about page but that's minor.
```

Version de GeoServer
@project.version@
Révision Git
@build.revision@
Build Date
@build.timestamp@ 
```
LGTM!

**Comment by pmauduit** [comment]
> as already seen, some versions arent properly shown on the about page but that's minor

I checked for the version, and I wonder if the issue is not also present upstream, just isolating the maven process:
https://github.com/geoserver/geoserver/blob/main/src/web/core/pom.xml#L154-L175

using `mvn process-resource` leads to have "....properties" in the target/ subdir, where I can still find `@project.version@` occurences.

**Comment by landryb** [comment]
> > as already seen, some versions arent properly shown on the about page but that's minor
> 
> I checked for the version, and I wonder if the issue is not also present upstream, just isolating the maven process: https://github.com/geoserver/geoserver/blob/main/src/web/core/pom.xml#L154-L175
> 

I've checked gs 2.22.2 vanilla in a tomcat, and i have the proper versions in the about page

image

**Comment by pmauduit** [comment]
testsuite is broken though (related to the ogcapi modules, but since this is supposed to be communautary modules / not maintained yet, I wonder if we should take care).

**Comment by pmauduit** [comment]
I checked the generated webapp, and I have not seen any inconsistencies (gs modules in v2.22.2 as expected, 4 modules are suffixed with "-georchestra", gt in v.28.2 wich is also expected).

**Comment by landryb** [comment]
> deployed on https://demo.georchestra.org/geoserver/web, works fine. as already seen, some versions arent properly shown on the about page but that's minor.
> 
> ```
> 
> Version de GeoServer
> @project.version@
> Révision Git
> @build.revision@
> Build Date
> @build.timestamp@ 
> ```

as found out by @pmauduit  caused by https://osgeo-org.atlassian.net/browse/GEOS-10871, can be worked around by replacing target by tasks in src/web/app/pom.xml (eg revert https://github.com/georchestra/geoserver/commit/d6a52bcf) or by forcing a newer version of the antrun plugin that support target ?

**Comment by pmauduit** [comment]
version issue should be fixed by https://github.com/georchestra/georchestra/commit/2c88b42b7f18444ee0745bee7c230baffbb6b698

**Comment by landryb** [comment]
Confirmed working on https://demo.georchestra.org/geoserver/web/wicket/bookmarkable/org.geoserver.web.AboutGeoServerPage?2&filter=false after `apt upgrade`:
```
Version de GeoServer
2.22.2-georchestra
Révision Git
9c06a6ea05986a5b0521efc8e33afc881aaa6723
Build Date
28-Feb-2023 09:42
Version de GeoTools
28.2 (rev 558cedba96f8d4c593a362982ce55b7a9e6942dc) 
```

**Pull request merged**
