### PR TITLE
console - link to org page from user's page

### PR DESCRIPTION
**Pull request by Gaetanbrl**
Ask reviewers here (can't see reviewers panel) @landryb @pierrejego

### CODE REVIEW

**Comment by pierrejego** [comment]
Bon,

je trouve des choses, mais bien compliqué....


On va faire simple, mais temporaire (très temporaire). tu désactivera le VPN après que la personne ait finit.


Passe ton l'adresse de ton VPN en 192.168.1.0, change l'adresse IP de l'automate en 192.168.1.207 (attention au conflit d'ip) et renvoie lui la conf du VPN.


Normalement en toute logique a devrait être bon. Par contre en faisant ça, il devrait avoir accès à tout ton réseau.


Et dès qu'il a finit desactive le VPN et ferme le port sur la livebox.


________________________________
De : Gaetanbrl <notifications@github.com>
Envoyé : vendredi 19 juillet 2019 15:00:29
À : georchestra/georchestra
Cc : Pierre Jégo - JDev; Mention
Objet : [georchestra/georchestra] Create link to access to org page from user's page directly georchest… (#2653)


Ask reviewers here (can't see reviewers panel) @landryb<https://github.com/landryb> @pierrejego<https://github.com/pierrejego>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/georchestra/georchestra/pull/2653

Commit Summary

  *   Create link to access to org page from user's page directly georchestra/georchestra#2618

File Changes

  *   M console/src/main/webapp/manager/app/components/user/user.es6<https://github.com/georchestra/georchestra/pull/2653/files#diff-0> (18)

Patch Links:

  *   https://github.com/georchestra/georchestra/pull/2653.patch
  *   https://github.com/georchestra/georchestra/pull/2653.diff

**Comment by landryb** [comment]
Tested working fine, @fvanderbiest @tonio does this look ok to merge for you ?

**Comment by tonio** [comment]
I find a bit confusing to have the link inside the widget: what about a link to open in a new tab as for the password?
Screenshot from 2019-07-22 11-56-34

**Comment by landryb** [comment]
> I find a bit confusing to have the link inside the widget: what about a link to open in a new tab as for the password?
> Screenshot from 2019-07-22 11-56-34

cf https://github.com/georchestra/georchestra/issues/2618#issuecomment-512724531 - it was evaluated, but after feedback from our users admin it's more natural to be able to click on the name instead of having yet another cryptic pictogram.

**Comment by landryb** [comment]
About opening in new tabs, #2449 tracks this :)

**Comment by fvanderbiest** [comment]
@Gaetanbrl can you assign a reviewer now ?

**Comment by Gaetanbrl** [comment]
I could assign the PR but not the Reviewer.
Maybe it's too late if the PR already exist ?
image

**Comment by tonio** [comment]
Not completely convinced with the appearance, but if we go that way, please consider cherry-picking https://github.com/georchestra/georchestra/commit/98cff466601d35876caa916caa5e168651da858a, formatter has superfluous complexity.

**Comment by fvanderbiest** [comment]
> Not completely convinced with the appearance

Same here. Can someone provide me with a better, bigger screenshot ?

**Comment by fvanderbiest** [comment]
> I could assign the PR but not the Reviewer.

OK, there's no easy way ... sigh

**Comment by landryb** [comment]
image

**Comment by fvanderbiest** [comment]
Waiting @Gaetanbrl takes into account @tonio 's remark regarding code complexity.
Thanks

**Comment by Gaetanbrl** [comment]
Cherry-pick takes into account @fvanderbiest

**Pull request merged**
