### PR TITLE
Osm2geor

### PR DESCRIPTION
**Pull request by fvanderbiest**
Porting @pmauduit 's addon to geOrchestra 14.12 and later (using OpenLayers' built in OSM format rather than a server side component).

It should work right now, but some more work is needed (translations, factorization ...)

The drawback of using client-side parsing of OSM data is that we miss the nice features that pmauduit had crafted on the server side (polygon detection and so on).

The good part is that it is already available for everyone.

### CODE REVIEW

**Comment by pmauduit** [comment]
Thanks for the initiative ;-)

Since you are doing everything from my code or porting some other parts client-side, I call myself out of the review (LGTM anyway :P)

**Comment by fvanderbiest** [comment]
Looks better now.
Missing spanish and german translations in manifest.json

**Comment by fvanderbiest** [comment]
Maybe we should investigate a bit more the OSM format options (eg: areaTags).

**Comment by fvanderbiest** [comment]
+ missing loading indicator

**Comment by fvanderbiest** [comment]
```
<fphg> petite idée d'amélioration : ajouter une liste de requêtes preset
<fphg> ... à prendre dans GEOR_config.js avec titre, request, style
```

**Comment by fvanderbiest** [comment]
Merci @Louca2014 pour
```
"es": {
            "OSM data": "Datos OSM",
            "This addon allows you to display OSM data in your map": "Esta herramienta le permite mostrar datos OSM en su mapa",
            "OSM to geOrchestra": "OSM a geOrchestra",
            "Query": "Consulta",
            "Style": "Estilo",
            "Keep previously loaded features": "Conservar los objetos existentes",
            "Execute": "Ejecutar",
            "Osm2Geor_HELP_URL": "http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide"
```

**Comment by fvanderbiest** [comment]
@jpklipfel : est-ce que CIGAL pourrait m'aider à traduire ceci en allemand ?

```json
        "de": {
            "OSM data": "Données OSM",
            "This addon allows you to display OSM data in your map": "Cet addon vous permet d'afficher des données OSM dans votre carte",
            "OSM to geOrchestra": "OSM vers geOrchestra",
            "Query": "Requête",
            "Style": "Style",
            "Keep previously loaded features": "Conserver les objets existants",
            "Execute": "Exécuter"
        }
```

Merci !

**Comment by jpklipfel** [comment]
Hello,


        "de": {

            "OSM data": "OSM-Daten",

            "This addon allows you to display OSM data in your map": "Dieses Add-on ermöglicht es die OSM-Daten in Ihrer Karte anzuzeigen",

            "OSM to geOrchestra": "OSM zu geOrchestra",

            "Query": "Abfrage",

            "Style": "Style",

            "Keep previously loaded features": "Zuvor hinzugeladene Objekte beibehalten",

            "Execute": "Ausführen"

        }

Merci au SIGRS/GISOR !
JPK

De : François Van Der Biest [mailto:notifications@github.com]
Envoyé : jeudi 24 septembre 2015 10:15
À : georchestra/georchestra
Cc : KLIPFEL Jean-Pascal
Objet : Re: [georchestra] Osm2geor (#1031)


@jpklipfel<https://github.com/jpklipfel> : est-ce que CIGAL pourrait m'aider à traduire ceci en allemand ?

        "de": {

            "OSM data": "Données OSM",

            "This addon allows you to display OSM data in your map": "Cet addon vous permet d'afficher des données OSM dans votre carte",

            "OSM to geOrchestra": "OSM vers geOrchestra",

            "Query": "Requête",

            "Style": "Style",

            "Keep previously loaded features": "Conserver les objets existants",

            "Execute": "Exécuter"

        }

Merci !

**Comment by fvanderbiest** [comment]
Looks better and better :-) 
Thanks everyone. Releasing soon...

**Comment by fvanderbiest** [comment]
Current status...
capture du 2015-09-25 22 09 20

**Comment by fphg** [comment]
sweet :)

**Comment by fvanderbiest** [comment]
Please help me provide default requests and / or styles, thanks :-)

**Comment by fvanderbiest** [comment]
I think it's good to go, now.
Please test and report issues before I merge into 14.12. Thanks.

**Comment by fphg** [comment]
Running on 15.06 dev.geobretagne.fr

the request list is nice and shows potential.
"label": "${_name}" is always returning "undefined". 'Undefined' should'nt be labelled.
changing to "label": "${_name}" shows some non-null labels. 
"Openlayers" stylename is cryptic (orange ?)

Anyway, the default conf is just a sample, now it's up to each SDI.
Great work !

**Comment by fvanderbiest** [comment]
> "label": "${_name}" is always returning "undefined". 'Undefined' should'nt be labelled.
> changing to "label": "${_name}" shows some non-null labels.

Strange, because c8c1958 should prevent this when using ```"${_name}"``` as label.
```"${name}"``` is the raw name, and it can be  ```undefined```, true

**Comment by fvanderbiest** [comment]
> Strange

OK, I get it. 
You probably did not update GEOR_util.js, which is required to get correct labels.

**Comment by fvanderbiest** [comment]
Cascade merge done => now available for everyone on 14.12, 15.06 and master.

**Comment by fvanderbiest** [comment]
Deployed to http://sdi.georchestra.org/mapfishapp/

**Comment by landryb** [comment]
```area["boundary"="administrative"]["admin_level"=8]{{BBOX}};``` queries administrative boundaries of level 8, but here JS blows my web browser even on a small bbox.

**Comment by fvanderbiest** [comment]
> but here JS blows my web browser even on a small bbox.

Not surprising ... ;-)
capture du 2015-09-28 10 45 57

**Comment by fvanderbiest** [comment]
Those who'd like to install this addon in their 14.12 or 15.06 instances should :
 * add the addon config in their mapfishapp's GEOR_custom.js file, see the related [documentation](https://github.com/georchestra/georchestra/blob/15.06/mapfishapp/src/main/webapp/app/addons/osm2geor/README.md#setup)
 * redeploy their security-proxy and mapfishapp from updated sources

**Comment by rafemoro** [comment]
Congratulations, I am now testeando, hopefully soon include GeoBolivia
captura de pantalla de 2015-09-29 12 09 24

**Comment by fvanderbiest** [comment]
> Congratulations, I am now testeando, hopefully soon include GeoBolivia

Happy to hear that it will be useful to people around the globe ;-)

**Comment by fvanderbiest** [comment]
Those who plan to use this addon to improve their own databases must not forget that the [OSM license](http://www.openstreetmap.org/copyright) is **viral**, which means that copying a single feature from the OSM database will require their own database to be redistributed under the terms of the ODBL as well.

**Comment by fvanderbiest** [comment]
... which does not mean that it cannot be used as a hint for missing features ...

**Pull request merged**
