### PR TITLE
security-proxy - Update dependencies

### PR DESCRIPTION
**Pull request by pmauduit**
Main proposal behind this PR:

* Updating dependencies, mainly migrating to Spring / Spring security 4
* Removing urlrewrite dependency
* Fixing logging (mismatch between log4j-over-slf4j and slf4j-log4j12)
* Refactor Proxy.java to remove unneeded complexity
* Adding javadoc on Proxy.java methods

This implies some changes though:
* In datadir / configuration files: the entrypoint for login `/j_spring_cas_security_check` is no longer valid, one should use `/login/cas` instead
* the entrypoint for logout changed as well: `/j_spring_security_logout` -> `/logout`

Tests:
* testsuite OK
* Mainly tested onto sandbox.georchestra.org (ansible / debian packages / tomcat based deploy)

still TODO:

* This would require a thorough test in a docker composition to ensure no regression on jetty-based deployments

### CODE REVIEW

**Comment by pmauduit** [comment]
Also important to mention here: this PR requires the SP to be built with Java8 (and consequently requires a Java8 runtime).

**Comment by pmauduit** [comment]
Do not merge now, as the PR currently breaks the basic-auth:

```
% curl -u testadmin 'https://sandbox.georchestra.org/geonetwork/srv/fre/xml.info?type=me'
Enter host password for user 'testadmin':
<?xml version="1.0" encoding="UTF-8"?>
<info>
  <me authenticated="false" />
  <env>
    <baseURL>/geonetwork</baseURL>
    <node>srv</node>
  </env>
</info>
```

**Comment by pmauduit** [comment]
Basic-auth now works on sandbox.g.o, thanks @jusabatier for the beta-testing / investigations

**Comment by fvanderbiest** [comment]
> Also important to mention here: this PR requires the SP to be built with Java8 (and consequently requires a Java8 runtime).

Can you please update https://github.com/georchestra/georchestra/blob/master/migrations/18.06/README.md in your PR ? Thanks !

**Comment by pmauduit** [comment]
> Can you please update https://github.com/georchestra/georchestra/blob/master/migrations/18.06/README.md in your PR ?

I was wondering if we should target it to 17.12 actually ? or maybe we can merge it for 18.06, then backport it ?

**Comment by fvanderbiest** [comment]
> maybe we can merge it for 18.06, then backport it ?

Yes, that's safer IMO !

**Comment by pmauduit** [comment]
> Can you please update https://github.com/georchestra/georchestra/blob/master/migrations/18.06/README.md in your PR ?

done

**Comment by pmauduit** [comment]
Still to be debugged under Jetty, as JSPs rendering and the ServletMapping annotation do not work as expected

**Comment by fvanderbiest** [comment]
`/j_spring_security_logout` does not exist anymore => these files require an update in this PR
```
config/defaults/geoserver-webapp/WEB-INF/classes/org/geoserver/web/GeoServerBasePage.html:        <a class="button-logout icon" href="j_spring_security_logout"><span><wicket:message key="logout">Logout</wicket:message></span></a>
docs/setup/apache.md:ProxyPass /j_spring_security_logout http://localhost:8180/j_spring_security_logout 
docs/setup/apache.md:ProxyPassReverse /j_spring_security_logout http://localhost:8180/j_spring_security_logout
extractorapp/src/main/webapp/app/js/GEOR_config.js:        LOGOUT_URL: "/j_spring_security_logout",
header/src/main/filtered-resources/WEB-INF/jsp/index.jsp:            <a href="<%=ldapadm %>/account/userdetails"><%=request.getHeader("sec-username") %></a><span class="light"> | </span><a href="/j_spring_security_logout"><fmt:message key="logout"/></a>
mapfishapp/src/main/webapp/app/js/GEOR_config.js:        LOGOUT_URL: "/j_spring_security_logout",
security-proxy/src/main/webapp/WEB-INF/urlrewrite.xml:        <to type="redirect" last="true">/j_spring_security_logout</to>
security-proxy/src/main/webapp/WEB-INF/urlrewrite.xml:        <from>^/(?!sec/|favicon.ico|receptor|j_spring_security_logout|j_spring_cas_security_check|header.jsp|_static/|cas-logout.jsp|403.jsp|404.jsp|casfailed.jsp)(.*)$</from>
```

**Comment by fvanderbiest** [comment]
> Still to be debugged under Jetty, as JSPs rendering and the ServletMapping annotation do not work as expected

eg view-source:https://lb.lb-http.geograndest.caas.camptocamp.com/toto/:
```
<c:choose>
    <c:when test='true'>
    <div id="go_head">
        <iframe src="/header/" style="width:100%;height:90px;border:none;overflow:none;" scrolling="no"></iframe>
    </div>
    </c:when>
</c:choose>
```

**Comment by fvanderbiest** [comment]
Might be due to `c` prefix not being defined in https://github.com/georchestra/georchestra/blob/17.12/config/defaults/security-proxy/header.jsp

**Comment by pmauduit** [comment]
Rebased to master this day.

**Pull request merged**
