### PR TITLE
Migration from Captcha V1 to Captcha V2

### PR DESCRIPTION
**Pull request by pierrejego**
New try for this PR :)

Ldapadmin.properties need to be updated with google remote url verification
New privateKey and publicKey have to be generated on google side 
see https://developers.google.com/recaptcha/docs/display

I didn't manage for the moment to mock server side call to verifiy recaptcha. I will probably need help to do it. So I add @ignore on several test to skip them for the moment.
I have check https://github.com/triologygmbh/reCAPTCHA-V2-java unit-test but they have created a specific http java object and add several librairies for mocking.  

If it's ok for you, I prefer not to add new librairie.

link to  #1001

Regards

### CODE REVIEW

**Comment by fvanderbiest** [comment]
We, at Camptocamp, understand the need to fix this asap, but are reluctant to merge this as is, since tests are ignored. We would really prefer you use the https://github.com/triologygmbh/reCAPTCHA-V2-java lib instead.
Let's have a phone call...

**Comment by pierrejego** [comment]
Ok no problem, but I will not be available before next Monday. I'll connect to IRC and we'll see.

For me test which are ignored doesn't have a real interrested.
We will need to change SLF4J version in ldapadmin to fit with the  https://github.com/triologygmbh/reCAPTCHA-V2-java api

**Comment by pierrejego** [comment]
Hello,
I am integrating the new api this morning, I was updating the test part when I had a problem with the JDK version.
This API is build with 1.8 java version, where I need 1.7 version for the 15.12 version ( current deploiement is made on 1.7 version with JCE Extension and I can't change it easily) 

If I try to launch tests I have an Unsupported major.minor version 52.0.

 Il will try to build with 1.8 and deploy using 1.7 to see if it works.

**Comment by fvanderbiest** [comment]
Thanks Pierre.
We'll merge this as is and port this to the newest branches.

**Comment by fvanderbiest** [comment]
geOrchestra master (= future 18.06) will require Java 8. 
Hence using the above lib would make sense from 18.06 on. Maintenance work should tackle this. ping @MaelREBOUX

**Comment by fvanderbiest** [comment]
@pmauduit can you cascade the changes to 16.12, 17.12 and master ? Thanks.

**Comment by fvanderbiest** [comment]
Please note that datadirs should be upgraded with eg https://github.com/georchestra/datadir/commit/0ff17b3d2e7fb265dbf64fc0c65f7ee01ef39dea

Adding this to the 18.06 migration notes with b0016798c98b768aca669c3a6b4bb5945ce68f16

**Pull request merged**
