### PR TITLE
[Console] Correction for external objectClass deletion

### PR DESCRIPTION
**Pull request by jusabatier**
Correct the problem for https://github.com/georchestra/georchestra/issues/3185

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks for the patch Julien !

**Comment by RemiDesgrange** [comment]
Thanks, Julien, for this patch. Could you add some unit test to your PR ? thanks !

**Comment by jusabatier** [comment]
Doesn't know how to do that :/

I know it's a bad point but I never did unit tests in my projects...

**Comment by jusabatier** [comment]
Wrong PR link, the #6 is here : https://github.com/jusabatier/georchestra/pull/6

**Comment by jusabatier** [comment]
What still have to do to merge it ?

I think this correction should be merged and backported ASAP as it can break other applications using same LDAP.

**Comment by fvanderbiest** [comment]
@RemiDesgrange can you have a look at the failures in the tests ? Thanks !

**Pull request closed without merging**
