### PR TITLE
WIP - Proxy trust another proxy

### PR DESCRIPTION
**Pull request by Vampouille**
Please do **not** merge because I need a deep review of modifications and unit test.

### CODE REVIEW

**Comment by Vampouille** [comment]
Can be tested with : 

```bash
curl -H "sec-username: testadmin" -H "sec-roles: ROLE_MOD_LDAPADMIN;ROLE_FONCIER_2009;ROLE_FONCIER_2014;ROLE_USER" -H "sec-org: psc" -H "sec-orgname: PSC" -H "sec-email: psc@georchestra.org" http://localhost:8180/extractorapp/admin/
```

**Comment by Vampouille** [comment]
Trust feature is now working, please review.

**Comment by Vampouille** [comment]
Maybe we need to check cookies header management ?

**Comment by Vampouille** [comment]
We need to merge `authentication-manager`:

```xml
     <s:authentication-manager alias="authenticationManager">
         <s:authentication-provider ref="preauthAuthProvider" />
         <s:authentication-provider ref='casAuthenticationProvider' />
         <s:authentication-provider ref='ldapAuthenticationProvider' />
     </s:authentication-manager>
```

**Comment by Vampouille** [comment]
We need to revert this commit : cb72fa5bf90d7340258f5ad64da624e7d1e8188e
See #1818 for details

**Comment by fvanderbiest** [comment]
Can we merge this now ?

**Comment by Vampouille** [comment]
> Can we merge this now ?

yes, it is already tested on some env.

**Comment by fvanderbiest** [comment]
OK, we need to add this to release notes.

**Pull request merged**
