### PR TITLE
QuickSearch Addon

### PR DESCRIPTION
**Pull request by fvanderbiest**
This addon is brought by Le Puy en Velay. 
It allows one to query layer objects across different services using "typeahead" search.

### CODE REVIEW

**Comment by fphg** [comment]
Hi
I understand the purpose, this is a nice addon. However it's a (more configurable) rewrite of the "referential search" feature. Is it a problem ?

**Comment by fvanderbiest** [comment]
> However it's a (more configurable) rewrite of the "referential search" feature.

True.

> Is it a problem ?

You mean: we now have two ways in mapfishapp to do the same thing:
 - one, which is mandatory, which is targeted at people with a mouse
 - an other one, optional, which is targeted at people with a keyboard and a good knowledge of the tool.

I don't really see a problem.
Of course, we could make all tabs from the tabpanel in the bottom right corner of the screen optional, by "addonizing" them, but it would be another task.

**Comment by fphg** [comment]
OK thanks

**Comment by fvanderbiest** [comment]
No negative feedback got from Le Puy en Velay => merging

**Pull request merged**
