### PR TITLE
add ability to launch custom scripts geowebcache

### PR DESCRIPTION
**Pull request by edevosc2c**
Was the last remaining component for adding support about custom scripts.

Related to https://github.com/georchestra/georchestra/pull/4083 and https://github.com/georchestra/georchestra/issues/4030

### CODE REVIEW

**Review by jeanmi151 — APPROVED** [review]
LGTM
Did you test it ?

**Comment by edevosc2c** [comment]
> LGTM Did you test it ?

yes works perfectly

**Comment by edevosc2c** [comment]
@f-necas good for merging?

**Comment by f-necas** [comment]
Yeah of course !

**Pull request merged**
