### PR TITLE
docker compose override and makefile for build

### PR DESCRIPTION
**Pull request by fvanderbiest**
A proposal for #1631

### CODE REVIEW

**Comment by Vampouille** [comment]
Why do you use a separate file ? What is the difference with `build` instruction in main `docker-compose.yml` file ?
@pmauduit do you think we can add webapp build with maven in `Makefile` ?

**Comment by fvanderbiest** [comment]
> Why do you use a separate file ? What is the difference with build instruction in main docker-compose.yml file ?

There's no difference, indeed. This is just to not add clutter into the main file.
Also we could take advantage of this file to override env vars for dev purposes... (later)

> do you think we can add webapp build with maven in Makefile ?

+1 same idea here after I submitted the PR.

**Comment by fvanderbiest** [comment]
Another idea would be to take advantage of this file to remove more clutter from the main compose file.
Namely these services could go into the override compose file:
```
  smtp:
    image: camptocamp/smtp-sink

  courier-imap:
    image: camptocamp/courier-imap
    volumes_from:
      - smtp:rw

  webmail:
    image: camptocamp/sqwebmail
    ports:
      - "8081:80"
    volumes_from:
      - smtp:rw

  geodata:
    image: georchestra/ssh_data
    ports:
      - "2222:22"
    volumes:
      - geoserver_geodata:/mnt/geoserver_geodata
```

Opinions ?

**Comment by fvanderbiest** [comment]
With https://github.com/georchestra/georchestra/pull/1634/commits/0a5d0db3edf0f0ff433a03448850eba951684f12, for those who would like to run all modules:
```
docker-compose -f docker-compose.yml -f docker-compose.other-apps.yml
```

**Comment by fvanderbiest** [comment]
7fbcfe2 adds more targets to Makefile.
Please review again.

**Comment by pmauduit** [comment]
> @pmauduit do you think we can add webapp build with maven in Makefile ?

That is fine for me

**Pull request merged**
