### PR TITLE
Update postgresql.md

### PR DESCRIPTION
**Pull request by MaxiReglisse**
i don't know if libpostgis-java is useful or not...
but postgis and postgresql-postgis are required !

### CODE REVIEW

**Comment by MaxiReglisse** [comment]
oh, i forgot "sudo" !!

**Comment by pmauduit** [comment]
> i don't know if libpostgis-java is useful or not...

The package provides some jars in the debian own local maven-repo (`/usr/share/maven-repo`)  as well as the postgis jdbc driver into `usr/share/java`.

Since these jars are usually provided by the webapps I don't think it is useful to also install the package.

**Comment by fvanderbiest** [comment]
-1 on this change since it is already mentioned in https://github.com/MaxiReglisse/georchestra/blob/14.12/doc/setup.md

**Comment by MaxiReglisse** [comment]
sorry, i was focused on https://github.com/MaxiReglisse/georchestra/blob/14.12/doc/setup/postgresql.md...

**Pull request closed without merging**
