### PR TITLE
Remove init-method and use PostConstruct annotation

### LINKED ISSUE #2504: Replace Spring init-method configuration parameter by @PostConstruct annotation
It seems to be recommended to use the [@PostConstruct](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-postconstruct-and-predestroy-annotations) annotation in the classes, instead of the Spring XML configuration `init-method` parameter.

See reasons here: https://stackoverflow.com/a/1089691/7351594.

### PR DESCRIPTION
**Pull request by RemiDesgrange**
Close #2504. 

I also could not resist refactor this little lambda :-)

### CODE REVIEW

**Comment by fvanderbiest** [comment]
mfapp and sp do not build ?

**Comment by RemiDesgrange** [comment]
See #3000

**Comment by RemiDesgrange** [comment]
@fvanderbiest I'm going to wait for CI to work again, then I'll merge this.

**Comment by fvanderbiest** [comment]
mapfishapp builds not, "ImportError: No module named virtualenv"
We might miss something like
```
    - name: setup Python 2.x (for jsbuild)
      uses: actions/setup-python@v1
      with:
        python-version: '2.x'

    - name: "installing jsbuild and virtualenv via pip"
      run: |
        pip install jsbuild
        pip install virtualenv
```
in https://github.com/georchestra/georchestra/blob/master/.github/workflows/mapfishapp.yml

**Comment by landryb** [comment]
> mapfishapp builds not, "ImportError: No module named virtualenv"

i had do do something similar in cadastrapp as it also uses jsbuild (from last millenium), maybe you want to reuse it.

**Comment by fvanderbiest** [comment]
> i had do do something similar in cadastrapp as it also uses jsbuild (from last millenium), maybe you want to reuse it.

Comes from there ;-)

**Comment by RemiDesgrange** [comment]
The python problem is, indeed a problem but does not fail the build (dunno why), The real problem si the lack of a dependency which I need to figure out.

**Comment by RemiDesgrange** [comment]
I forgot to rebase on master. Now OK

**Comment by fvanderbiest** [comment]
Thanks !

**Pull request merged**
