### PR TITLE
Console/fix import csv

### PR DESCRIPTION
**Pull request by isanchez-c2c**
- windows adds carriage returns on csv, we need to parse them out 
- replace function readAsBinaryString (which already has been deprecated and is not used in the project) by readAsText

### CODE REVIEW

**Comment by landryb** [comment]
will fix #2971, thanks !

**Review by tonio — APPROVED** [review]
Untested, but looks good, thanks! :shipit:

**Comment by fvanderbiest** [comment]
Good job Ivanne ! Thanks :-)

**Comment by fvanderbiest** [comment]
Ported to `20.1.x` for `20.1.2` and `master`

**Pull request merged**
