### PR TITLE
CI - Packaging - use a dedicated variable (#1878)

### PR DESCRIPTION
**Pull request by pmauduit**
See #1878 and #1877

tests: build-time on catalogapp:

```
mvn clean package deb:package -PdebianPackage
```

OK

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Can we use the branch name instead, taking into account the fact that the datadir branch name to use is the same as the geOrchestra branch name ?

**Comment by pmauduit** [comment]
> Can we get the current branch name instead, taking into account the fact that the datadir branch name to use is the same as the geOrchestra branch name ?

It might mess up if a new branch is created (for a PR for example). So we should leave it for the packaging purposes (and not apply the same variable for docker containers, for instance).

**Comment by fvanderbiest** [comment]
What about `<dockerDatadirScmVersion>docker-${packageDatadirScmVersion}</dockerDatadirScmVersion>` ?

**Comment by pmauduit** [comment]
> What about <dockerDatadirScmVersion>docker-${packageDatadirScmVersion}</dockerDatadirScmVersion> ?

ok

**Comment by fvanderbiest** [comment]
Also https://github.com/georchestra/geonetwork/blob/georchestra-gn3-16.12/web/pom.xml#L1027 ?

**Comment by pmauduit** [comment]
See added commit

**Comment by fvanderbiest** [comment]
LGTM

**Comment by fvanderbiest** [comment]
Merged into master with ea72ee774009b2cba113ea219b6ac6415bd8c01c

**Pull request merged**
