### PR TITLE
Fix stats result range by handling timezone

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
I'm not agree with codacy analyse. Can we turn some checks off ?

**Comment by Vampouille** [comment]
linked with : https://github.com/georchestra/datadir/pull/38

**Comment by fvanderbiest** [comment]
@pmauduit : can you review this one ?
Many thanks.

**Comment by pmauduit** [comment]
> @pmauduit : can you review this one ?

Was there a linked issue ? hard to tell why this modification was needed without context

**Comment by pmauduit** [comment]
Ok, for the record (reported on a issue from a private repository):

```
There is an issue with the timezone, logs are stored in UTC but the dates in the query are in UTC+2.

The group by query by hour works on 12h, stats for 13h (1PM) are counted onto the 01h slice.
```

Anyway, the current PR looks good to me.

**Pull request merged**
