### PR TITLE
console - allow bigger organization thumbnails

### PR DESCRIPTION
**Pull request by jeanmi151**
this is to increase by the default (200000) value of maxFormContentSize in console

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Why did we close it ?
I think 200kb is too small, and 5Mb too big for the organization thumbnail

**Comment by fvanderbiest** [comment]
I think we should go on with this, and set the limit to 1Mb

**Comment by jeanmi151** [comment]
because this is only for docker/containers specific

**Comment by fvanderbiest** [comment]
At least it will work in this context !

**Comment by fvanderbiest** [comment]
I think the value of 5Mb is too big, we should set it at 1Mb

**Review by f-necas — APPROVED** [review]

**Pull request merged**
