### PR TITLE
update documentation to modify password rotation policy

### PR DESCRIPTION
**Pull request by jeanmi151**
this is some comment to update the rotation password policy

### CODE REVIEW

**Comment by jeanmi151** [comment]
@marwanehcine any suggestion of you validate this PR ?

**Comment by fvanderbiest** [comment]
LGTM, thanks JM.
I'll just rephrase it a bit afterwards.

**Comment by jeanmi151** [comment]
so can I merge and you will do modification later ?

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/georchestra/pull/4023

**Pull request merged**
