### PR TITLE
Remove unused files in GeoServer

### PR DESCRIPTION
**Pull request by severo**
Be careful - it does not change the current behaviour, but maybe the
00-geoserver-bootstrap script was intended to be run (but was not).

In that case, we instead should add something like

```
ENTRYPOINT [ "/docker-entrypoint.sh" ]
```

inside the Dockerfile.

### CODE REVIEW

**Comment by severo** [comment]
See #2226

**Comment by fvanderbiest** [comment]
You're completely right, it's meant to be run in container entrypoint.
I do not understand how this got removed at some point.

**Comment by severo** [comment]
OK, I will add it

**Comment by severo** [comment]
Changed to #2460

**Pull request closed without merging**
