### PR TITLE
[GEOSERVER] Bump geoserver to 2.24

### PR DESCRIPTION
**Pull request by f-necas**
This PR bumps geoserver to latest 2.24 stable : 2.24.2

### CODE REVIEW

**Comment by landryb** [comment]
https://geoserver.org/announcements/2023/10/15/geoserver-2-24-0-released.html has some upgrade notes that mention the now enabled by default url check security, cf https://docs.geoserver.org/maintain/en/user/security/urlchecks.html

if ppl use external SLD or SVG in resources, they should care about that.. something to stress in the relnotes.

the PR builds fine here using `openjdk 17.0.10 2024-01-16` (the default on debian 12) and it packages fine
```
[WARNING] dpkg-deb: building package 'georchestra-geoserver' in '/data/src/georchestra/georchestra/geoserver/webapp/target/georchestra-geoserver_99.master.202403131435~805cf32-1_all.deb'.
```

when trying to run it within tomcat 9, after a restart it fails to start the webapp (reproducible):
```
ERROR StatusLogger Caught java.lang.AbstractMethodError setting feature http://xml.org/sax/features/external-general-entities to false on DocumentBuilderFactory org.apache.xerces.jaxp.DocumentBuilderFactoryImpl@7f9c5f39: java.lang.AbstractMethodError: Receiver class org.apache.xerces.jaxp.DocumentBuilderFactoryImpl does not define or inherit an implementation of the resolved method 'abstract void setFeature(java.lang.String, boolean)' of abstract class javax.xml.parsers.DocumentBuilderFactory.

ERROR  [context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is java.lang.NoSuchMethodError: 'void org.springframework.expression.spel.support.StandardTypeConverter.<init>(java.util.function.Supplier)'
```
i've tried rm -Rf on the previous webapp but that doesnt help.

From my understanding the first error is a conflict between xerces and java, so i removed `webapps/geoserver/WEB-INF/lib/xercesImpl-2.6.2.jar` from the webapp and it solved the first error message... so something to remove from `pom.xml` somewhere ?

for the second message, i'd guess this has to do with the spring jars that end up in the war, which seem to be .. of various different versions ?
```
webapps/geoserver/WEB-INF/lib/spring-aop-5.3.27.jar
webapps/geoserver/WEB-INF/lib/spring-beans-5.3.27.jar
webapps/geoserver/WEB-INF/lib/spring-context-5.3.27.jar
webapps/geoserver/WEB-INF/lib/spring-context-support-5.3.27.jar
webapps/geoserver/WEB-INF/lib/spring-core-5.3.27.jar
webapps/geoserver/WEB-INF/lib/spring-expression-5.2.24.RELEASE.jar
webapps/geoserver/WEB-INF/lib/spring-jdbc-5.3.27.jar
webapps/geoserver/WEB-INF/lib/spring-ldap-core-2.4.1.jar
webapps/geoserver/WEB-INF/lib/spring-security-config-5.7.10.jar
webapps/geoserver/WEB-INF/lib/spring-security-core-5.7.10.jar
webapps/geoserver/WEB-INF/lib/spring-security-crypto-5.7.10.jar
webapps/geoserver/WEB-INF/lib/spring-security-ldap-5.7.10.jar
webapps/geoserver/WEB-INF/lib/spring-security-web-5.7.10.jar
webapps/geoserver/WEB-INF/lib/spring-tx-5.2.24.RELEASE.jar
webapps/geoserver/WEB-INF/lib/spring-web-5.2.24.RELEASE.jar
webapps/geoserver/WEB-INF/lib/spring-webmvc-5.3.27.jar
```
maybe the overrides in https://github.com/georchestra/georchestra/blob/master/geoserver/pom.xml#L19 need updating ?

**Comment by landryb** [comment]
retrying with
```
diff --git a/geoserver/pom.xml b/geoserver/pom.xml
index 736a09446..e176f0044 100644
--- a/geoserver/pom.xml
+++ b/geoserver/pom.xml
@@ -9,16 +9,16 @@
   <properties>
     <skipTests>true</skipTests>
     <gs.version>2.24.2</gs.version>
-    <gt.version>28.5</gt.version>
+    <gt.version>30.2</gt.version>
     <geofence.version>3.5.1</geofence.version>
     <jetty.version>9.4.48.v20220622</jetty.version>
     <marlin.version>0.9.3</marlin.version>
-    <jackson.version>2.13.5</jackson.version>
+    <jackson2.version>2.15.2</jackson2.version>
     <packageDatadirScmVersion>master</packageDatadirScmVersion>
     <server>generic</server>
     <!-- overrides the versions provided by spring-boot in the geOrchestra root pom -->
-    <spring.version>5.2.24.RELEASE</spring.version>
-    <spring-security.version>5.1.13.RELEASE</spring-security.version>
+    <spring.version>5.3.27</spring.version>
+    <spring-security.version>5.7.10</spring-security.version>
     <hibernate.version>3.6.9.Final</hibernate.version>
```
wont solve the xercesImpl jar but at least aligns versions with the ones in https://github.com/georchestra/geoserver/blob/2.24.2-georchestra-24.0.x/src/pom.xml#L90

**Comment by landryb** [comment]
> retrying with
> 
> ```
> diff --git a/geoserver/pom.xml b/geoserver/pom.xml
> index 736a09446..e176f0044 100644
> --- a/geoserver/pom.xml
> +++ b/geoserver/pom.xml
> @@ -9,16 +9,16 @@
>    <properties>
>      <skipTests>true</skipTests>
>      <gs.version>2.24.2</gs.version>
> -    <gt.version>28.5</gt.version>
> +    <gt.version>30.2</gt.version>
>      <geofence.version>3.5.1</geofence.version>
>      <jetty.version>9.4.48.v20220622</jetty.version>
>      <marlin.version>0.9.3</marlin.version>
> -    <jackson.version>2.13.5</jackson.version>
> +    <jackson2.version>2.15.2</jackson2.version>
>      <packageDatadirScmVersion>master</packageDatadirScmVersion>
>      <server>generic</server>
>      
> -    <spring.version>5.2.24.RELEASE</spring.version>
> -    <spring-security.version>5.1.13.RELEASE</spring-security.version>
> +    <spring.version>5.3.27</spring.version>
> +    <spring-security.version>5.7.10</spring-security.version>
>      <hibernate.version>3.6.9.Final</hibernate.version>
> ```
> 
> wont solve the xercesImpl jar but at least aligns versions with the ones in https://github.com/georchestra/geoserver/blob/2.24.2-georchestra-24.0.x/src/pom.xml#L90

with that diff, the resulting deb/war still complains loudly at startup when loading log4j2 xml configs:
```
ERROR Caught java.lang.AbstractMethodError setting feature http://apache.org/xml/features/nonvalidating/load-external-dtd to false on DocumentBuilderFactory org.apache.xerces.jaxp.DocumentBuilderFactoryImpl@61cad704: java.lang.AbstractMethodError: Receiver class org.apache.xerces.jaxp.DocumentBuilderFactoryImpl does not define or inherit an implementation of the resolved method 'abstract void setFeature(java.lang.String, boolean)' of abstract class javax.xml.parsers.DocumentBuilderFactory. java.lang.AbstractMethodError: Receiver class org.apache.xerces.jaxp.DocumentBuilderFactoryImpl does not define or inherit an implementation of the resolved method 'abstract void setFeature(java.lang.String, boolean)' of abstract class javax.xml.parsers.DocumentBuilderFactory.
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.setFeature(XmlConfiguration.java:206)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.disableDtdProcessing(XmlConfiguration.java:201)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.newDocumentBuilder(XmlConfiguration.java:188)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:91)
        at org.geoserver.logging.GeoServerXMLConfiguration.<init>(GeoServerXMLConfiguration.java:72)
        at org.geoserver.logging.LoggingUtilsDelegate$1.<init>(LoggingUtilsDelegate.java:317)
        at org.geoserver.logging.LoggingUtilsDelegate.configureFromLog4j2(LoggingUtilsDelegate.java:316)
        at org.geoserver.logging.LoggingUtilsDelegate.configureGeoServerLogging(LoggingUtilsDelegate.java:124)
        at org.geoserver.logging.LoggingUtilsDelegate.initLogging(LoggingUtilsDelegate.java:552)
        at org.geoserver.logging.LoggingUtils.initLogging(LoggingUtils.java:173)
        at org.geoserver.logging.LoggingStartupContextListener.contextInitialized(LoggingStartupContextListener.java:78)
```
but the webapp resumes starting fine, and the admin web interface shows up.

**Comment by landryb** [comment]
now that i'm testing at runtime behind the s-p from 23.0 (yeah, i know), it seems there's something missing for auth, because when properly logged in as `testadmin` against CAS, the s-p sends the proper `sec-*` headers to tomcat (checked with tcpdump)
```
sec-tel: tel
sec-roles: ROLE_SUPERUSER;ROLE_MAPSTORE_ADMIN;ROLE_USER;ROLE_ADMINISTRATOR;ROLE_CAD_CNIL2;ROLE_GN_ADMIN;ROLE_DRIVE
sec-org: psc
sec-email: admin@craig.fr
sec-lastname: ADMIN
sec-firstname: Test
sec-username: testadmin
sec-orgname: Project Steering Committee
```
but the webapp doesn't show the admin bits in the left pane. Was there some headers reconfig in the gateway that changed this ?

the geoserver datadir still has this config:
```
/srv/data/geoserver $cat security/filter/proxy/config.xml
<requestHeaderAuthentication>
  <id>-e3457ae:13cce0c47c6:-7fef</id>
  <name>proxy</name>
  <className>org.geoserver.security.filter.GeoServerRequestHeaderAuthenticationFilter</className>
  <roleSource class="org.geoserver.security.config.PreAuthenticatedUserNameFilterConfig$PreAuthenticatedUserNameRoleSource">Header</roleSource>
  <rolesHeaderAttribute>sec-roles</rolesHeaderAttribute>
  <principalHeaderAttribute>sec-username</principalHeaderAttribute>
</requestHeaderAuthentication>
```

**Comment by f-necas** [comment]
I'm behind the gateway and have the same problem by now

**Comment by landryb** [comment]
after logging out from CAS & logging in again as testadmin, i have the admin menus. 

I still have a strange thing, at some point the web admin page does a request for `/geoserver/web/''` which gets an error message in the browser console, and a maybe related vomit in the log:
```
13 Mar 16:19:00 WARN   [lang.WicketObjects] - Could not resolve class ['']
java.lang.ClassNotFoundException: ''
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.apache.wicket.application.AbstractClassResolver.resolveClass(AbstractClassResolver.java:101)
        at org.apache.wicket.core.util.lang.WicketObjects.resolveClass(WicketObjects.java:71)
        at org.apache.wicket.core.request.mapper.AbstractComponentMapper.getPageClass(AbstractComponentMapper.java:120)
        at org.apache.wicket.core.request.mapper.BookmarkableMapper.parseRequest(BookmarkableMapper.java:114)
        at org.apache.wicket.core.request.mapper.AbstractBookmarkableMapper.mapRequest(AbstractBookmarkableMapper.java:345)
        at org.apache.wicket.request.mapper.CompoundRequestMapper.mapRequest(CompoundRequestMapper.java:147)
        at org.geoserver.web.DynamicCryptoMapper.mapRequest(DynamicCryptoMapper.java:49)
```
but the request comes from `header.js` and since im not running the full 24 stack nor the gateway i'm not suprised by this error. At least now i can poke in the menus and see what changed :)

**Comment by landryb** [comment]
looking at the 2.23 & 2.24 changelogs:
- https://geoserver.org/announcements/2023/04/05/geoserver-2-23-0-released.html
- https://geoserver.org/announcements/2023/10/15/geoserver-2-24-0-released.html

i see lots of improvements on the OCGAPI module, so maybe it's time to retest it ? it was disabled in #3883.. i know there's the data api module but...

**Comment by landryb** [comment]
with https://github.com/georchestra/geoserver/commit/772f91e4680cda876ace44a7290662aa273c0265 cherrypicked on top i think we're good to merge :)

**Review by pmauduit — APPROVED** [review]

**Review by landryb — APPROVED** [review]

**Comment by landryb** [comment]
\o/

**Comment by landryb** [comment]
@f-necas i dunno if that's expected but this PR isn't present in the 24.0 branch in the georchestra repo, apparently 24.0 was branched off earlier than this PR merge.

**Comment by f-necas** [comment]
Yes I've just put documentation in 24 branch. It will be rebased on master when it's ready :)

Just [4 issues](https://github.com/georchestra/georchestra/milestone/42) and we're good to go !

**Pull request merged**
