### PR TITLE
Display last user connection & account creation date from OpenLDAP attributes

### PR DESCRIPTION
**Pull request by landryb**
will fix/implement #2271 but more work needed.

### CODE REVIEW

**Comment by jusabatier** [comment]
Is it possible to also retrieve and display account creation date ?

It should help to identify recently created accounts with no connection.

**Comment by jusabatier** [comment]
Maybe you should just add some documentation on how to install the LDAP overlay in install doc : 

https://github.com/georchestra/georchestra/blob/master/docs/setup/openldap.md

**Comment by landryb** [comment]
> Maybe you should just add some documentation on how to install the LDAP overlay in install doc :
> 
> https://github.com/georchestra/georchestra/blob/master/docs/setup/openldap.md

like https://github.com/georchestra/georchestra/blob/e0e4590a533d55472929de65808d41d8717a8924/docs/setup/openldap.md#the-lastbind-overlay ? i've rewritten a bit the doc while here in c11e41f

**Comment by fvanderbiest** [comment]
So, you say that ldap writes are "buffered" in some way ? I'm really concerned about this for the basic-auth case specifically...

**Comment by landryb** [comment]
> So, you say that ldap writes are "buffered" in some way ? I'm really concerned about this for the basic-auth case specifically...

what is your concern ? the code of the overlay only writes if the attribute value is older than the configured precision (cf https://github.com/openldap/openldap/blob/master/contrib/slapd-modules/lastbind/lastbind.c#L25 & https://github.com/openldap/openldap/blob/master/contrib/slapd-modules/lastbind/lastbind.c#L139), to avoid updating the attribute at each hit of a basic-auth ogc service for example. If the last auth was more recent than the precision, no write happens, there's no "buffering".

**Comment by landryb** [comment]
image

**Review by fvanderbiest — APPROVED** [review]
LGTM once translations have been provided

**Pull request merged**
