### PR TITLE
gwc - manages new georchestra header (#4227)

### PR DESCRIPTION
**Pull request by pmauduit**
Supports the new webcomponent based georchestra header in the geowebcache app.

Tests: 
* verify OK
* mainly runtime, switching the flag in the default.properties datadir file to check the behaviour.

### CODE REVIEW

**Comment by f-necas** [comment]
I think we may include stylesheets and other thing by default ?  
Like `<geor-header active-app="geowebcache" legacy-header="@useLegacyHeader@" legacy-url="@headerUrl@" style="width:100%;height:@headerHeight@px;border:none;" logo-url="@logoUrl@" stylesheet="@georchestraStylesheet@"></geor-header>`

**Comment by pmauduit** [comment]
> I think we may include stylesheets and other thing by default ?

Then we'd need to document the properties into the datadir's default.properties:
https://github.com/georchestra/datadir/blob/master/default.properties#L20-L47

what are the default values for the different properties ?

**Comment by pmauduit** [comment]
> what are the default values for the different properties ?

https://github.com/georchestra/datadir/blob/master/default.properties#L20-L47

**Review by f-necas — APPROVED** [review]
Thanks @pmauduit. I'll have to find a way to implement geowebcache inside the new header 😄

**Pull request merged**
