### PR TITLE
Remove UTF8 filter. Fix web.xml encoding in some webapps.

### PR DESCRIPTION
**Pull request by RemiDesgrange**

### CODE REVIEW

**Comment by RemiDesgrange** [comment]
(remember to remove `package-lock.json` no idea how it got into that)

**Comment by fvanderbiest** [comment]
Can you explain in your PR why the filter is not needed anymore ? also why encoding can be changed ? 

Rule of thumb for future PRs - we have to be kind to our future selfs ;-)

Thanks

**Comment by fvanderbiest** [comment]
Up for a review. Thanks.

**Comment by RemiDesgrange** [comment]
There is a linked issue (#2996) that explain everything, but it took me 5 minutes in the new github UI to find it so makeing it more clearly accessible :sweat_smile:

**Review by pmauduit — APPROVED** [review]

**Pull request merged**
