### PR TITLE
Add links to export all/filtered users to csv/vcf with POST

### PR DESCRIPTION
**Pull request by Gaetanbrl**
Issue #2278

* Only use POST request without URL params.

This PR seems to be in redundancy with [the Geo2france backlog](https://github.com/orgs/georchestra/projects/7#card-15166711). 
So, you could close or approve this work according to the upcoming progress.

_Ask manual reviewers (no reviewers panel available) @pierrejego @landryb_

### CODE REVIEW

**Comment by landryb** [comment]
dunno which pr should be rebased on top of which but what's in this one works fine.

**Comment by fvanderbiest** [comment]
> IMHO this should be rebased on top of #2652, use ids from the selection & implement action in the selection dropdown.

Agreed: having a manual selection of users seems a more powerful approach.
Closing this one.

**Comment by fvanderbiest** [comment]
Sorry Gaetan. Hope you don't mind.

**Comment by Gaetanbrl** [comment]
> Agreed: having a manual selection of users seems a more powerful approach

No problem @fvanderbiest.
But for the bothe are powerfull. The filter field help users to select a large number of users that could be more slow with checkbox selection (click by click). 
Manual selection is really usefull if you want to select only some users (for exemple, inside a filter's results or inside role members).

**Pull request closed without merging**
