### PR TITLE
[Mapfishapp] Contexts CSS update

### PR DESCRIPTION
**Pull request by jusabatier**
This rule allows to align thumbs correctly when title is on multiple lines in contexts selection.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Looks good, but is the window size fixed, so that there are always 4 thumbs in a line ?

**Comment by jusabatier** [comment]
No, you're right, the window size is not fixed.

What about the comportement on : https://opendata.agglo-lepuyenvelay.fr/mapfishapp/ ?

The thumbs resize with the window width, so there are always 4 per row.

If it's OK for you I can add the CSS in this PR

**Comment by jusabatier** [comment]
Finally, the use of the new CSS3 flex display property is a better solution I think.

**Comment by fvanderbiest** [comment]
Thanks a lot Julien !

**Pull request merged**
