### PR TITLE
docs - information on releases

### PR DESCRIPTION
**Pull request by fvanderbiest**
Documents the new release scheme

### CODE REVIEW

**Comment by fvanderbiest** [comment]
See https://github.com/georchestra/georchestra/blob/releases/docs/releases.md

**Comment by fvanderbiest** [comment]
Image source is https://docs.google.com/presentation/d/1d97tOn_gYk5s9DzblpcazKEPTd1w-mf9kQOuw19inw4/edit (for the record)

**Comment by landryb** [comment]
just realized that the buildbot will need work to adapt to the new branch naming... since it no longer matches the release being built but its a prefix..

**Comment by landryb** [comment]
buildbot has a new job (https://packages.georchestra.org/bot/builders/buildjob-20.0.x/builds/0, access limited) for this branch (and deploys debian pkg in the `20.0.x` branch of the repo), but strangely it still produces pkgs for master..
```
20.0.x|main|amd64: georchestra-analytics 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-atlas 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-cas 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-console 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-extractorapp 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-geonetwork3 3.8.2.202002050918~134bfd5
20.0.x|main|amd64: georchestra-geoserver 99.master.202002050916~6ede375
20.0.x|main|amd64: georchestra-geowebcache 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-header 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-mapfishapp 99.master.202002050918~6ede375
20.0.x|main|amd64: georchestra-security-proxy 99.master.202002050918~6ede375
```
i guess that's because we're still on 20.0-SNAPSHOT per 32636eac and not a real version like in fe31be7 ? as long as the `-SNAPSHOT` prefix is removed when the release is final...

**Comment by fvanderbiest** [comment]
> i guess that's because we're still on 20.0-SNAPSHOT per [32636ea](https://github.com/georchestra/georchestra/commit/32636eacc74c1bdb376fc65fad9579585f7b4f32) and not a real version like in [fe31be7](https://github.com/georchestra/georchestra/commit/fe31be7a2d021bf98909f22ecb29f6e127feaf25) ? as long as the `-SNAPSHOT` prefix is removed when the release is final...

Yes, the release has not been published yet. It will be a tag, and the `version` will be set to `20.0.0`.

**Comment by landryb** [comment]
https://packages.georchestra.org/bot/wars/20.0.x/ has wars :)

**Pull request merged**
