### PR TITLE
changing make file to reflect git branch on building

### PR DESCRIPTION
**Pull request by RemiDesgrange**
Adding this maven option will also work with fixed version (ex: 19.04,
19.06 etc..)

### CODE REVIEW

**Comment by RemiDesgrange** [comment]
Yess that was my intitial thought :-)

**Comment by pmauduit** [comment]
Did you try it ? since I cannot find any occurence of `dockerImageTags` in the pom.xml, I wonder how it will substitute:
https://github.com/georchestra/georchestra/blob/master/mapfishapp/pom.xml#L544

I'd have put a dockerImageTag property which by default would have taken project.version, if you want to keep the possibility to override it (anyway, it's still overrideable using -DdockerImageName and fully giving a custom image name + tag).

**Comment by RemiDesgrange** [comment]
Yup I tested it ;-)

**Comment by pmauduit** [comment]
Ok, I was not aware of the possibility by the spotify docker maven plugin to override the tag this way, sorry about that.

**Pull request merged**
