### PR TITLE
Fix email sending issue for multiple recipients

### PR DESCRIPTION
**Pull request by marwanehcine**
On  this PR, mail sending issue for multiple recipients is fixed.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks Marwane. 
It used to work on previous geOrchestra versions - is it a regression ?

**Comment by marwanehcine** [comment]
> Thanks Marwane. It used to work on previous geOrchestra versions - is it a regression ? Shall we backport it ?

I'm not sure if it is a regression, but It was not working when there is more than one receiver, for only one receiver it is working, problem appears when more than one receivers.

**Review by pmauduit — APPROVED** [review]
LGTM but I was wondering if there was not a way to write the loop using streams instead, in a more java8-ish approach.

**Comment by pmauduit** [comment]
> I'm not sure if it is a regression, but It was not working when there is more than one receiver, for only one receiver it is working, problem appears when more than one receivers.

This is strange, I am pretty sure we were able to send mails to several recipients in the past. Looking at the `javax.mail.internet.MimeMessage` implementation, several `To: ` mail headers should have been appended.

**Comment by fvanderbiest** [comment]
> This is strange, I am pretty sure we were able to send mails to several recipients in the past

100% agree

**Pull request merged**
