### PR TITLE
Upgrade GeoServer to 2.18.3

### PR DESCRIPTION
**Pull request by jeanpommier**
addresses https://github.com/georchestra/georchestra/issues/3381

### CODE REVIEW

**Comment by jeanpommier** [comment]
Shall we merge it ?

**Comment by fvanderbiest** [comment]
Yep. Can you port to master, so we don't have a lower version in master than in 20.1.x ? 
Ideally, we should have 2.19.1 on master ...
Thanks.

**Comment by jeanpommier** [comment]
Master already uses 2.18.3 I believe

**Comment by fvanderbiest** [comment]
Oh, sorry, I got lost

**Pull request merged**
