### PR TITLE
Jdk 11 compat

### PR DESCRIPTION
**Pull request by RemiDesgrange**
Supersede #3183

### CODE REVIEW

**Comment by pmauduit** [comment]
Current status with `mvn clean install -fae`:
```
[INFO] Mapfishapp Webapp 21.0-SNAPSHOT .................... FAILURE [ 32.495 s]
[INFO] Analytics webapp 21.0-SNAPSHOT ..................... FAILURE [  6.690 s]
[INFO] Data-Feeder microservice 21.0-SNAPSHOT ............. FAILURE [01:25 min]
[INFO] Data-Feeder (web ui) 21.0-SNAPSHOT ................. FAILURE [ 13.983 s]
```

I'm still wondering if we go this way, if geonetwork also would need to migrate to jdk11. I prepared a PR about it here:
https://github.com/georchestra/geonetwork/pull/191/files
but it will require to disable the failing test (workaround for date/time parsing/calculation on one harverster), and be suggested upstream as well.

**Comment by pmauduit** [comment]
testsuite for mfapp is broken in java11 because of xerces / xercesImpl, something resembling as described here: https://issues.apache.org/jira/browse/XERCESJ-1706
The dependency is transitively added by mfprint (org.mapfish.print:print-lib). We might need to add a custom profile for jdk11 redefining the dependency to the print with an extra exclude:

```
[INFO] +- org.mapfish.print:print-lib:jar:2.1.1-georchestra:compile
[...]
[INFO] |  +- xerces:xercesImpl:jar:2.4.0:compile
```

**Comment by pmauduit** [comment]
It will also require to *check every dockerfiles* and make sure they are using a jetty based image with a sufficiently recent jre before merging.

**Comment by RemiDesgrange** [comment]
Fix #2489

**Review by pmauduit — APPROVED** [review]

**Pull request merged**
