### PR TITLE
console - filter org/role members

### PR DESCRIPTION
**Pull request by Gaetanbrl**
Link to  georchestra/georchestra#2469
Ask manual reviewers (no reviewers panel) @pierrejego @landryb

### CODE REVIEW

**Comment by landryb** [comment]
tested, works fine. thanks!

**Comment by RemiDesgrange** [comment]
@Gaetanbrl can you rebase against master to see if test pass in travis. Test fail bc of too much line. This issue has been resolved.

**Comment by fvanderbiest** [comment]
> @Gaetanbrl can you rebase against master to see if test pass in travis. Test fail bc of too much line. This issue has been resolved.

This PR is client-side only ...

**Comment by Gaetanbrl** [comment]
Need last test and clean, since last commit in #2657 (include suspicious merge).

**Pull request merged**
