### PR TITLE
Add backport-bot

### PR DESCRIPTION
**Pull request by f-necas**
Add backport bot to georchestra. 
https://github.com/camptocamp/backport-action

TODO : 
- [ ] Create `${{ secrets.GITHUB_TOKEN }}` token

### CODE REVIEW

**Comment by f-necas** [comment]
You can add a label, e.g. `backport 23.0.x `and it creates a PR on requested branch automatically.

https://github.com/camptocamp/backport-action

**Comment by fvanderbiest** [comment]
Thanks.

May require some explanatory words on https://github.com/georchestra/georchestra/blob/master/CONTRIBUTING.md for instance.

**Comment by pmauduit** [comment]
> [ ] Create `${{ secrets.GITHUB_TOKEN }}` token

As discussed, a token is already provided by github in the GHAs. We could either:
* upgrade the token's rights so that it could be used for what is intended here (RW)
* adding some code in the yaml workflow file

Source: https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp

@f-necas WDYT ?

**Comment by jahow** [comment]
> > [ ] Create `${{ secrets.GITHUB_TOKEN }}` token
> 
> As discussed, a token is already provided by github in the GHAs. We could either:
> 
>     * upgrade the token's rights so that it could be used for what is intended here (RW)
> 
>     * adding some code in the yaml workflow file
> 
> 
> Source: https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
> 
> @f-necas WDYT ?

Stopping by to mention that we had this issue in geonetwork-ui, the "free" github token provided for each actions run does not have permission to create branches and PR so we had to create a token from someone who has these rights on the repo. I'd be interested to know if there is a better/other way, thanks!

**Comment by f-necas** [comment]
I updated the permissions, it may be good with this ones ?

**Comment by pmauduit** [comment]
> it may be good with this ones ?

from what I understood from the doc, I'd expect so

**Comment by f-necas** [comment]
Let's try it

**Pull request merged**
