### PR TITLE
all - maven repo cleanup

### PR DESCRIPTION
**Pull request by pmauduit**
* boundlessgeo repositories do not respond anymore
* osgeo now set up a nexus

tests: only a mvn clean install -DskipTests, the purpose here is just to make sure we can fetch the dependencies. It seems to pass with no modification on GN, but this submodule will probably require a cleanup as well.

### CODE REVIEW

**Comment by pmauduit** [comment]
Doing a try on geonetwork, don't merge yet (note: I could not find how to set the PR as draft)

**Comment by pmauduit** [comment]
I'll launch a build elsewhere (in a fresh maven docker image for instance), to make sure that everything can be retrieved.

**Comment by landryb** [comment]
> Doing a try on geonetwork, don't merge yet (note: I could not find how to set the PR as draft)

top right under the reviewer menu, 'convert to draft' ? :)

**Comment by pmauduit** [comment]
> top right under the reviewer menu, 'convert to draft' ? :)

right, thanks, I was expecting something near the [edit] button instead

**Comment by pmauduit** [comment]
Since the PRs from dependabot are being merged, some parts of this one becomes somehow useless:
* https://github.com/georchestra/georchestra/pull/3069
* https://github.com/georchestra/georchestra/pull/3068

**Comment by fvanderbiest** [comment]
@pmauduit can you fix the conflicts ? Thanks.

**Comment by pmauduit** [comment]
> @pmauduit can you fix the conflicts ? Thanks.

done

**Comment by pmauduit** [comment]
needs to be ported back to 20.0.x probably

**Pull request merged**
