### PR TITLE
[console] Libs upgrade

### PR DESCRIPTION
**Pull request by tonio**

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Oops, there's a conflict now ...

**Comment by landryb** [comment]
Fwiw there are a bunch of pending console prs (i'm specifically thinking about #2777) so it would be nice to refrain from gratuitous style changes until they're merged.. thanks !

**Comment by fvanderbiest** [comment]
> it would be nice to refrain from gratuitous style changes until they're merged

Most of these changes are not gratuitous...

**Comment by Gaetanbrl** [comment]
Gratuitous or not, the fact is it's a real nightmare to merge after styles modification.

**Comment by tonio** [comment]
The ˋstandard` tool has been upgraded, you just have to run it with ˋ—fix` option to have the same code base.

**Comment by Gaetanbrl** [comment]
> The ˋstandard tool has been upgraded, you just have to run it with ˋ—fix

Thanks.
I think, it's npm command ?

**Comment by Gaetanbrl** [comment]
Don't see anything about npm command in the console doc... sorry.

**Comment by Gaetanbrl** [comment]
Ok i have this command from manager doc : [here](https://github.com/georchestra/georchestra/tree/master/console/src/main/webapp/manager).

**Comment by tonio** [comment]
Yep, that's it.

**Pull request merged**
