### PR TITLE
Add support for s3-geotiff coverage stores

### LINKED ISSUE #2225: s3-geotiff conflicts with geofence
When creating a new s3-geotiff datastore:
```
Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: URLConfigurationSource [url=jar:file:/var/lib/jetty/webapps/geoserver/WEB-INF/lib/geofence-persistence-3.2-20180503.181323-25.jar!/geofence-ehcache.xml]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:626)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:391)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:269)
	at org.geotools.s3.cache.CacheManagement.buildCache(CacheManagement.java:62)
	at org.geotools.s3.cache.CacheManagement.<init>(CacheManagement.java:38)
	at org.geotools.s3.cache.CacheManagement.<clinit>(CacheManagement.java:29)
	... 158 more
```

### PR DESCRIPTION
**Pull request by groldan**
Adds support for configuring and serving S3 GeoTiffs in GeoServer.

Fixes #2225

This PR goes together with https://github.com/georchestra/datadir/pull/140 for `datadir`

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks Gabriel.
IIUC, this means the jar will only be distributed in docker images.
Would it take long to also add it to deb and wars artifacts ?

**Comment by groldan** [comment]
Hi @fvanderbiest, I haven't thought about dev and war artifacts, as I've only worked on the docker images so far, didn't even take them into account :)
I'll have to check it out but I'm guessing it shouldn't be hard?

**Comment by fvanderbiest** [comment]
> I haven't thought about dev and war artifacts, as I've only worked on the docker images so far, didn't even take them into account :)

Haha
If you add it to the wars and debs, that would be awesome. Thanks !

**Comment by groldan** [comment]
amended the commit to include the patched jar in the final .war
Getting it (and every other extension) inside the war and deb builds depends on fixing #2549

**Comment by groldan** [comment]
See #2550 for the fix that includes the geoserver extensions in the war and deb builds too

**Comment by fvanderbiest** [comment]
Thanks Gabriel !

**Pull request merged**
