### PR TITLE
Geoserver 2.16.1

### PR DESCRIPTION
**Pull request by pmauduit**
Upgrading to GeoServer 2.16.1. Some of the georchestra customizations have been kept:

* header integration
* patch to avoid a loop when slaves are notified that the GS datadir changed (which was modifying the datadir then creating an infinite loop)
* Changing default cached layer hashmap size from 100 elements to 400

The following have been dropped:

* possibility to override some jars in the lib subdirectory

Tests: only compilation with testsuite OK, runtime tested in a docker image (JRE11), UI launches fine, but I have not dug further for now. No GS modules tested so far either.

### CODE REVIEW

**Comment by landryb** [comment]
fwiw, georchestra/mapstore2-georchestra also requires a recent geoserver for timeline and authkey support, cant remember the exact version but a recent 2.15 or even 2.16 would be nice !

**Comment by fvanderbiest** [comment]
Excellent, thanks Pierre !
Can you also check (at least manually) that extensions we usually build are working fine ?
```
        "control-flow",
        "css",
        "gdal",
        "geofence",
        "inspire",
        "jp2k",
        "mbtiles",
        "monitor",
        "pyramid",
        "wps",
        "wps-download",
        "libjpeg-turbo",
        "vectortiles"
```

**Comment by landryb** [comment]
and eventually look at #2826 ? ;)

**Comment by pmauduit** [comment]
> Can you also check (at least manually) that extensions we usually build are working fine ?

These extensions are just maven profiles which add some extra dependencies available on the default maven repositories to the webapp. So, it is mainly a matter of checking if they are still available on the repo upstream and in the expected version (mvnrepository.com is my friend)

**Comment by fvanderbiest** [comment]
Tested on a dev environment with the above mentioned plugins. 
Looks good to me but a second review would be nice.

**Comment by groldan** [comment]
A few notes:

* At startup, the following error can be disregarded, guess it should be logged at the INFO level without stack trace from geoserver:
```
geoserver_1                 | Exception in thread "Thread-43" java.lang.NoSuchMethodError: 'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)'
geoserver_1                 | 	at oshi.jna.platform.linux.Libc.<clinit>(Libc.java:38)
geoserver_1                 | 	at oshi.software.os.linux.LinuxOperatingSystem.getProcessId(LinuxOperatingSystem.java:344)
geoserver_1                 | 	at org.geoserver.system.status.OSHISystemInfoCollector.lambda$new$0(OSHISystemInfoCollector.java:70)
geoserver_1                 | 	at java.base/java.lang.Thread.run(Unknown Source)
```

* Logs are not logged to the console, we should enable "log to stdout" by default. And probably _only_ log to the console, being in a dockerized environment.

**Comment by landryb** [comment]
>     * Logs are not logged to the console, we should enable "log to stdout" by default. And probably _only_ log to the console, being in a dockerized environment.

please, no. Not everyone is running in a dockerized environment, and traditional-style has always been to log to a file.

**Comment by fvanderbiest** [comment]
> We'd need to investigate further before upgrading to java 11.

Thanks Gabriel. 
We'll migrate to java 11 in a second time.

**Pull request merged**
