### PR TITLE
rename the doc folder into docs

### PR DESCRIPTION
**Pull request by fvanderbiest**
With https://github.com/blog/2228-simpler-github-pages-publishing in mind ...

"Selecting `master branch /docs folder` will publish from the /docs folder of your master branch. This lets you maintain documentation and code together on one branch, and open source maintainers can accept contributions for both in a single pull request."

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Not concluding ... http://georchestra.github.io/georchestra/ redirects to http://www.georchestra.org/georchestra/ which ends up in 404

Must interfere with https://github.com/georchestra/georchestra.github.io/blob/master/CNAME

**Comment by fvanderbiest** [comment]
Ho, I did not see that we can have control on this ...
screenshot from 2016-08-17 20-39-12
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by fvanderbiest** [comment]
What about `docs.georchestra.org` ?

**Comment by landryb** [comment]
> What about docs.georchestra.org ?

Definitely :) Github is a feature maze...

**Comment by landryb** [comment]
Out of curiosity, what's published in which form ? plain html, github-flavoured markdown, pdfs ?

**Comment by fvanderbiest** [comment]
Seems like the markdown files in the doc folder are rendered into html and published as such.
eg index.md -> index.html

**Comment by fvanderbiest** [comment]
screenshot from 2016-08-22 10-56-53

I guess we have to declare the subdomain in the DNS. 
ping @pmauduit or @fphg ?

**Comment by pmauduit** [comment]
```
% host docs.georchestra.org
Host docs.georchestra.org not found: 3(NXDOMAIN)
```

Presumably, we need a A or a CNAME record for docs.georchestra.org, pointing onto the github infrastructure, this should be documented somewhere in the docker help pages. I don't have any credentials to manage the DNS, I leave the issue to @fphg ;-)

**Comment by fvanderbiest** [comment]
> Out of curiosity, what's published in which form ? plain html, github-flavoured markdown, pdfs ?

More information [here](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages)

**Comment by fvanderbiest** [comment]
From https://help.github.com/articles/troubleshooting-custom-domains/#dns-record-doesnt-point-to-githubs-server, docs.georchestra.org should point to 192.30.252.153 / 192.30.252.154 (github servers)

**Pull request merged**
