### PR TITLE
viewer - fix the language we extend in GeoExt i18n.

### LINKED ISSUE #2355: viewer - GeoExt i18n files extended to "fr" instead of correct language
See https://github.com/georchestra/georchestra/blob/6482f4fdaa2bf874c73ef20529556339fc4a1023/mapfishapp/src/main/webapp/app/js/GEOR_Lang/es.js#L533

It should be `es`, not `fr`.

The same applies for all the files of the https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/js/GEOR_Lang/ directory.

### PR DESCRIPTION
**Pull request by severo**
Fixes #2355.

### CODE REVIEW

**Comment by severo** [comment]
@fvanderbiest you want me to backport to 15.06?

**Comment by severo** [comment]
(and following?)

**Comment by fvanderbiest** [comment]
cherry-picking for 15.12 would be great indeed.

Also merge 15.12 into 16.12
then 16.12 into 17.12
then 17.12 into 18.06
then 18.06 into master ... Or you can leave it to me if you prefer...

**Comment by severo** [comment]
OK, I will do.

**Comment by severo** [comment]
OK:

- 15.06: https://github.com/georchestra/georchestra/pull/2361
- 15.12: https://github.com/georchestra/georchestra/commit/b08611c5345cf2f72ba03e4d82206a127972457b
- 16.12: https://github.com/georchestra/georchestra/commit/147ebd34e0202cd518c46048e8275d2f405cf4d0
- 17.12: https://github.com/georchestra/georchestra/commit/8fe1bc864a9c8b0d6cbf28c760e72e1880c46264
- 18.06: https://github.com/georchestra/georchestra/commit/a4322a67d13e0cef82596544530198110a85151b

**Comment by fvanderbiest** [comment]
and 18.06 into master...

**Comment by severo** [comment]
ahhhhhhh last commit was an error (merging 17.12 to 18.06)

**Comment by fvanderbiest** [comment]
no worries then

**Comment by severo** [comment]
> and 18.06 into master...

There are a lot of changes not merged into master, I prefer to let you manage this.

**Comment by fvanderbiest** [comment]
okay !

**Comment by fvanderbiest** [comment]
Done with e53fbc036ae3b35d83a8fd817d9569e6f66c11d5

**Pull request merged**
