### PR TITLE
Limit memory usage of webapps with XMX environement variable

### PR DESCRIPTION
**Pull request by Vampouille**
* `sh -c` is used to replace environment variable
* `exec` is used to keep PID 1 on java process

### CODE REVIEW

**Comment by Vampouille** [comment]
This PR is linked with https://github.com/georchestra/geonetwork/pull/39

**Comment by fvanderbiest** [comment]
Same idea as https://github.com/georchestra/ansible/pull/41#issuecomment-224810965 : I'm wondering if we could loop on an array of options.

**Comment by fvanderbiest** [comment]
In addition, I think it would be safer to have Xms independant from Xmx

**Comment by pmauduit** [comment]
After reading official Oracle doc: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

```
For server deployments, -Xms and -Xmx are often set to the same value. See the section "Ergonomics" in Java SE HotSpot Virtual Machine Garbage Collection Tuning Guide at http://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/index.html.
```

**Comment by fvanderbiest** [comment]
OK, this means that, for production deployments, it's better to have XMS = XMX.
But for dev or demo purposes, It might be a pain to consume all available memory at startup.

**Comment by pmauduit** [comment]
Tested locally, seems working fine

**Pull request merged**
