### PR TITLE
Admin console for master branch

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
We need to protect new console url on security proxy. Maybe here : https://github.com/georchestra/datadir/blob/master/security-proxy/security-mappings.xml

**Comment by fvanderbiest** [comment]
What is the URL for the console ?

Maybe we should integrate it into the header too...

**Comment by pmauduit** [comment]
> We need to protect new console url on security proxy. Maybe here : https://github.com/georchestra/datadir/blob/master/security-proxy/security-mappings.xml

Right (for the datadir mode), also here for the non-datadir mode:
https://github.com/georchestra/georchestra/blob/15.12/security-proxy/src/main/webapp/WEB-INF/applicationContext-security.xml#L44-L71

**Comment by pmauduit** [comment]
some platforms (rennes-metropole) are overriding this file in their configuration profile, this should be addressed there as well

**Comment by tonio** [comment]
URL for the header : `/ldapadmin/console/public/#/home`

**Comment by fvanderbiest** [comment]
> URL for the header : /ldapadmin/console/public/#/home

Can we make it easier to remember, eg `/ldapadmin/console/` ? (`#/home` appended on load, this is ok)
Maybe @Vampouille ?

**Comment by Vampouille** [comment]
I added security mapping for console :
* https://github.com/georchestra/datadir/commit/f9b50aa546b7c54d0619a77c7150cdc6605614ac
* https://github.com/georchestra/datadir/commit/c7b57ddfc5861ae7be9fcec8439897e344e36f22
* https://github.com/georchestra/datadir/commit/4958e8d827f559b1c7d184f46ecb07275c2d100f

So modifications in following branches :
* docker
* master
* docker-master

@fvanderbiest , @pmauduit can you post-review those commits ?

**Comment by pmauduit** [comment]
> @fvanderbiest , @pmauduit can you post-review those commits ?

It does not harm to add some rules in these places, so that looks ok to me.

**Comment by fvanderbiest** [comment]
LGTM ;-)

**Pull request merged**
