### PR TITLE
Add support to change user login

### PR DESCRIPTION
**Pull request by tonio**
See #1689 

Looks like there's no format check for uid on the server-side… I can add one client-side if needed but it won't be enough imho.

### CODE REVIEW

**Comment by landryb** [comment]
Basic testing, works as expected, and correctly renames the LDAP object via MODRDN. What do you mean by 'format check for uid' ? Ie only numbers/letters/point & no crazy special chars? `makeUid` in the account creation JSP page does some but its clientside and doesnt 'fix' what a user could put in the field... cf https://github.com/georchestra/georchestra/blob/master/console/src/main/webapp/WEB-INF/views/validation.jsp#L225 too

**Comment by tonio** [comment]
For now, what you give to server is saved, regardless of symbols/accentuated chars in it. I think there should be restrictions, at least the same as the one in `makeUid`.

**Comment by fvanderbiest** [comment]
> I can add one client-side if needed

Yes, I think we should have the same checks on uid everywhere. 

https://github.com/georchestra/georchestra/blob/b069c0499c269d86f17a28d987ca88061ed58a83/console/src/main/webapp/WEB-INF/views/validation.jsp#L225-L240 looks good to me.

**Comment by landryb** [comment]
Add a comment in both places reminding the next developer who changes the rule to update the other spot :)

**Comment by landryb** [comment]
Retested tip of this branch, renaming works fine, uid is changed, and group membership is updated, ie the roles & org objects have the 'new' dn as member; :+1: to merge.

A comment linking the two places would still be welcome :)

**Pull request merged**
