### PR TITLE
[console] unbreak account creation form after 8df191a (fixes #2522)

### LINKED ISSUE #2522: 8df191a broke account creation form
```
** Root cause is: Impossible de compiler la classe pour la JSP: 

Une erreur s'est produite à la ligne: 149 dans le fichier jsp: /WEB-INF/views/createAccountForm.jsp
readonlyUid cannot be resolved to a variable
```

unsurprising, since 8df191a only took care of `headerHeight`/`headerUrl`

### PR DESCRIPTION
**Pull request by landryb**
add missing readonlyUid spring placeholder

please test it at runtime and merge to 18.12 :)

### CODE REVIEW

**Comment by fvanderbiest** [comment]
PR should have targeted 18.12 ?

**Comment by severo** [comment]
Yes

**Comment by severo** [comment]
Note to myself: the file already contains a lot of placeholders... First understand the difference with the Spring placeholders before reviewing.

**Comment by severo** [comment]
> First understand the difference with the Spring placeholders before reviewing.

OK they come from the model used in the form and defined in the https://github.com/georchestra/georchestra/blob/18.12/console/src/main/java/org/georchestra/console/ws/newaccount/NewAccountFormController.java class.

I hope mixing placeholders from different sources will not end conflicts (general comment, not related directly to this PR)

**Comment by severo** [comment]
Backported to 18.12 with https://github.com/georchestra/georchestra/commit/cbc488979cf28d6e881f9d031a735c6d9e8b93e6. Note: I should have cherry-picked first in 18.12, PR, and then merged into master... Nevermind.

**Pull request merged**
